// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using UpstoxClient.Client;
using UpstoxClient.Model;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace UpstoxClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IHistoryV3Api : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        HistoryV3ApiEvents Events { get; }

        /// <summary>
        /// Historical candle data
        /// </summary>
        /// <remarks>
        /// Get OHLC values for all instruments for the present trading day with expanded interval options.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetHistoricalCandleDataApiResponse"/>&gt;</returns>
        Task<IGetHistoricalCandleDataApiResponse> GetHistoricalCandleDataAsync(string? instrumentKey = default, string? unit = default, int? interval = default, string? toDate = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Historical candle data
        /// </summary>
        /// <remarks>
        /// Get OHLC values for all instruments for the present trading day with expanded interval options.
        /// </remarks>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetHistoricalCandleDataApiResponse"/>?&gt;</returns>
        Task<IGetHistoricalCandleDataApiResponse?> GetHistoricalCandleDataOrDefaultAsync(string? instrumentKey = default, string? unit = default, int? interval = default, string? toDate = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Historical candle data
        /// </summary>
        /// <remarks>
        /// Get OHLC values for all instruments for the present trading day with expanded interval options
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="fromDate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetHistoricalCandleDataWithFromDateApiResponse"/>&gt;</returns>
        Task<IGetHistoricalCandleDataWithFromDateApiResponse> GetHistoricalCandleDataWithFromDateAsync(string? instrumentKey = default, string? unit = default, int? interval = default, string? toDate = default, string? fromDate = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Historical candle data
        /// </summary>
        /// <remarks>
        /// Get OHLC values for all instruments for the present trading day with expanded interval options
        /// </remarks>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="fromDate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetHistoricalCandleDataWithFromDateApiResponse"/>?&gt;</returns>
        Task<IGetHistoricalCandleDataWithFromDateApiResponse?> GetHistoricalCandleDataWithFromDateOrDefaultAsync(string? instrumentKey = default, string? unit = default, int? interval = default, string? toDate = default, string? fromDate = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Intra day candle data
        /// </summary>
        /// <remarks>
        /// Get OHLC values for all instruments for the present trading day
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetIntraDayCandleDataApiResponse"/>&gt;</returns>
        Task<IGetIntraDayCandleDataApiResponse> GetIntraDayCandleDataAsync(string? instrumentKey = default, string? unit = default, int? interval = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Intra day candle data
        /// </summary>
        /// <remarks>
        /// Get OHLC values for all instruments for the present trading day
        /// </remarks>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetIntraDayCandleDataApiResponse"/>?&gt;</returns>
        Task<IGetIntraDayCandleDataApiResponse?> GetIntraDayCandleDataOrDefaultAsync(string? instrumentKey = default, string? unit = default, int? interval = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IGetHistoricalCandleDataApiResponse"/>
    /// </summary>
    public interface IGetHistoricalCandleDataApiResponse : UpstoxClient.Client.IApiResponse, IMethodNotAllowed<UpstoxClient.Model.ApiGatewayErrorResponse?>, IBadRequest<UpstoxClient.Model.ApiGatewayErrorResponse?>, IInternalServerError<UpstoxClient.Model.ApiGatewayErrorResponse?>, ITooManyRequests<UpstoxClient.Model.ApiGatewayErrorResponse?>, ILocked<UpstoxClient.Model.ApiGatewayErrorResponse?>, IUnprocessableContent<UpstoxClient.Model.ApiGatewayErrorResponse?>, IOk<UpstoxClient.Model.GetHistoricalCandleResponse?>
    {
        /// <summary>
        /// Returns true if the response is 405 MethodNotAllowed
        /// </summary>
        /// <returns></returns>
        bool IsMethodNotAllowed { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 423 Locked
        /// </summary>
        /// <returns></returns>
        bool IsLocked { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }

        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="IGetHistoricalCandleDataWithFromDateApiResponse"/>
    /// </summary>
    public interface IGetHistoricalCandleDataWithFromDateApiResponse : UpstoxClient.Client.IApiResponse, IMethodNotAllowed<UpstoxClient.Model.ApiGatewayErrorResponse?>, IBadRequest<UpstoxClient.Model.ApiGatewayErrorResponse?>, IInternalServerError<UpstoxClient.Model.ApiGatewayErrorResponse?>, ITooManyRequests<UpstoxClient.Model.ApiGatewayErrorResponse?>, ILocked<UpstoxClient.Model.ApiGatewayErrorResponse?>, IUnprocessableContent<UpstoxClient.Model.ApiGatewayErrorResponse?>, IOk<UpstoxClient.Model.GetHistoricalCandleResponse?>
    {
        /// <summary>
        /// Returns true if the response is 405 MethodNotAllowed
        /// </summary>
        /// <returns></returns>
        bool IsMethodNotAllowed { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 423 Locked
        /// </summary>
        /// <returns></returns>
        bool IsLocked { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }

        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="IGetIntraDayCandleDataApiResponse"/>
    /// </summary>
    public interface IGetIntraDayCandleDataApiResponse : UpstoxClient.Client.IApiResponse, IMethodNotAllowed<UpstoxClient.Model.ApiGatewayErrorResponse?>, IBadRequest<UpstoxClient.Model.ApiGatewayErrorResponse?>, IInternalServerError<UpstoxClient.Model.ApiGatewayErrorResponse?>, ITooManyRequests<UpstoxClient.Model.ApiGatewayErrorResponse?>, ILocked<UpstoxClient.Model.ApiGatewayErrorResponse?>, IUnprocessableContent<UpstoxClient.Model.ApiGatewayErrorResponse?>, IOk<UpstoxClient.Model.GetIntraDayCandleResponse?>
    {
        /// <summary>
        /// Returns true if the response is 405 MethodNotAllowed
        /// </summary>
        /// <returns></returns>
        bool IsMethodNotAllowed { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 423 Locked
        /// </summary>
        /// <returns></returns>
        bool IsLocked { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }

        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class HistoryV3ApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetHistoricalCandleData;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetHistoricalCandleData;

        internal void ExecuteOnGetHistoricalCandleData(HistoryV3Api.GetHistoricalCandleDataApiResponse apiResponse)
        {
            OnGetHistoricalCandleData?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetHistoricalCandleData(Exception exception)
        {
            OnErrorGetHistoricalCandleData?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetHistoricalCandleDataWithFromDate;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetHistoricalCandleDataWithFromDate;

        internal void ExecuteOnGetHistoricalCandleDataWithFromDate(HistoryV3Api.GetHistoricalCandleDataWithFromDateApiResponse apiResponse)
        {
            OnGetHistoricalCandleDataWithFromDate?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetHistoricalCandleDataWithFromDate(Exception exception)
        {
            OnErrorGetHistoricalCandleDataWithFromDate?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetIntraDayCandleData;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetIntraDayCandleData;

        internal void ExecuteOnGetIntraDayCandleData(HistoryV3Api.GetIntraDayCandleDataApiResponse apiResponse)
        {
            OnGetIntraDayCandleData?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetIntraDayCandleData(Exception exception)
        {
            OnErrorGetIntraDayCandleData?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class HistoryV3Api : IHistoryV3Api
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<HistoryV3Api> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public HistoryV3ApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="OauthTokenProvider"/>
        /// </summary>
        public TokenProvider<OAuthToken> OauthTokenProvider { get; }

        /// <summary>
        /// The sandbox configuration
        /// </summary>
        private readonly ISandboxConfiguration _sandboxConfiguration;

        /// <summary>
        /// Initializes a new instance of the <see cref="HistoryV3Api"/> class.
        /// </summary>
        /// <returns></returns>
        public HistoryV3Api(ILogger<HistoryV3Api> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, HistoryV3ApiEvents historyV3ApiEvents,
            TokenProvider<OAuthToken> oauthTokenProvider, ISandboxConfiguration sandboxConfiguration)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<HistoryV3Api>();
            HttpClient = httpClient;
            Events = historyV3ApiEvents;
            OauthTokenProvider = oauthTokenProvider;
            _sandboxConfiguration = sandboxConfiguration;
        }


        partial void FormatGetHistoricalCandleData(ref string? instrumentKey, ref string? unit, ref int? interval, ref string? toDate);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        private void AfterGetHistoricalCandleDataDefaultImplementation(IGetHistoricalCandleDataApiResponse apiResponseLocalVar, string? instrumentKey, string? unit, int? interval, string? toDate)
        {
            bool suppressDefaultLog = false;
            AfterGetHistoricalCandleData(ref suppressDefaultLog, apiResponseLocalVar, instrumentKey, unit, interval, toDate);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        partial void AfterGetHistoricalCandleData(ref bool suppressDefaultLog, IGetHistoricalCandleDataApiResponse apiResponseLocalVar, string? instrumentKey, string? unit, int? interval, string? toDate);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        private void OnErrorGetHistoricalCandleDataDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string? instrumentKey, string? unit, int? interval, string? toDate)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetHistoricalCandleData(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, instrumentKey, unit, interval, toDate);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        partial void OnErrorGetHistoricalCandleData(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string? instrumentKey, string? unit, int? interval, string? toDate);

        /// <summary>
        /// Historical candle data Get OHLC values for all instruments for the present trading day with expanded interval options.
        /// </summary>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetHistoricalCandleDataApiResponse"/>&gt;</returns>
        public async Task<IGetHistoricalCandleDataApiResponse?> GetHistoricalCandleDataOrDefaultAsync(string? instrumentKey = default, string? unit = default, int? interval = default, string? toDate = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetHistoricalCandleDataAsync(instrumentKey, unit, interval, toDate, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Historical candle data Get OHLC values for all instruments for the present trading day with expanded interval options.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetHistoricalCandleDataApiResponse"/>&gt;</returns>
        public async Task<IGetHistoricalCandleDataApiResponse> GetHistoricalCandleDataAsync(string? instrumentKey = default, string? unit = default, int? interval = default, string? toDate = default, System.Threading.CancellationToken cancellationToken = default)
        {
            SandboxValidationUtils.ValidateSandboxMode(_sandboxConfiguration, "GetHistoricalCandleDataAsync");
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatGetHistoricalCandleData(ref instrumentKey, ref unit, ref interval, ref toDate);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v3/historical-candle/{instrumentKey}/{unit}/{interval}/{to_date}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/v3/historical-candle/{instrumentKey}/{unit}/{interval}/{to_date}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BinstrumentKey%7D", Uri.EscapeDataString(instrumentKey.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bunit%7D", Uri.EscapeDataString(unit.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Binterval%7D", Uri.EscapeDataString(interval.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bto_date%7D", Uri.EscapeDataString(toDate.ToString()));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "*/*",
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<GetHistoricalCandleDataApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetHistoricalCandleDataApiResponse>();
                        GetHistoricalCandleDataApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v3/historical-candle/{instrumentKey}/{unit}/{interval}/{to_date}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetHistoricalCandleDataDefaultImplementation(apiResponseLocalVar, instrumentKey, unit, interval, toDate);

                        Events.ExecuteOnGetHistoricalCandleData(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetHistoricalCandleDataDefaultImplementation(e, "/v3/historical-candle/{instrumentKey}/{unit}/{interval}/{to_date}", uriBuilderLocalVar.Path, instrumentKey, unit, interval, toDate);
                Events.ExecuteOnErrorGetHistoricalCandleData(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetHistoricalCandleDataApiResponse"/>
        /// </summary>
        public partial class GetHistoricalCandleDataApiResponse : UpstoxClient.Client.ApiResponse, IGetHistoricalCandleDataApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetHistoricalCandleDataApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetHistoricalCandleDataApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetHistoricalCandleDataApiResponse(ILogger<GetHistoricalCandleDataApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetHistoricalCandleDataApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetHistoricalCandleDataApiResponse(ILogger<GetHistoricalCandleDataApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 405 MethodNotAllowed
            /// </summary>
            /// <returns></returns>
            public bool IsMethodNotAllowed => 405 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 405 MethodNotAllowed
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? MethodNotAllowed()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsMethodNotAllowed
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 405 MethodNotAllowed and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryMethodNotAllowed([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = MethodNotAllowed();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)405);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? TooManyRequests()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 423 Locked
            /// </summary>
            /// <returns></returns>
            public bool IsLocked => 423 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 423 Locked
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? Locked()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsLocked
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 423 Locked and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryLocked([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = Locked();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)423);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? UnprocessableContent()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.GetHistoricalCandleResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.GetHistoricalCandleResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out UpstoxClient.Model.GetHistoricalCandleResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetHistoricalCandleDataWithFromDate(ref string? instrumentKey, ref string? unit, ref int? interval, ref string? toDate, ref string? fromDate);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="fromDate"></param>
        private void AfterGetHistoricalCandleDataWithFromDateDefaultImplementation(IGetHistoricalCandleDataWithFromDateApiResponse apiResponseLocalVar, string? instrumentKey, string? unit, int? interval, string? toDate, string? fromDate)
        {
            bool suppressDefaultLog = false;
            AfterGetHistoricalCandleDataWithFromDate(ref suppressDefaultLog, apiResponseLocalVar, instrumentKey, unit, interval, toDate, fromDate);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="fromDate"></param>
        partial void AfterGetHistoricalCandleDataWithFromDate(ref bool suppressDefaultLog, IGetHistoricalCandleDataWithFromDateApiResponse apiResponseLocalVar, string? instrumentKey, string? unit, int? interval, string? toDate, string? fromDate);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="fromDate"></param>
        private void OnErrorGetHistoricalCandleDataWithFromDateDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string? instrumentKey, string? unit, int? interval, string? toDate, string? fromDate)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetHistoricalCandleDataWithFromDate(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, instrumentKey, unit, interval, toDate, fromDate);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="fromDate"></param>
        partial void OnErrorGetHistoricalCandleDataWithFromDate(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string? instrumentKey, string? unit, int? interval, string? toDate, string? fromDate);

        /// <summary>
        /// Historical candle data Get OHLC values for all instruments for the present trading day with expanded interval options
        /// </summary>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="fromDate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetHistoricalCandleDataWithFromDateApiResponse"/>&gt;</returns>
        public async Task<IGetHistoricalCandleDataWithFromDateApiResponse?> GetHistoricalCandleDataWithFromDateOrDefaultAsync(string? instrumentKey = default, string? unit = default, int? interval = default, string? toDate = default, string? fromDate = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetHistoricalCandleDataWithFromDateAsync(instrumentKey, unit, interval, toDate, fromDate, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Historical candle data Get OHLC values for all instruments for the present trading day with expanded interval options
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="toDate"></param>
        /// <param name="fromDate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetHistoricalCandleDataWithFromDateApiResponse"/>&gt;</returns>
        public async Task<IGetHistoricalCandleDataWithFromDateApiResponse> GetHistoricalCandleDataWithFromDateAsync(string? instrumentKey = default, string? unit = default, int? interval = default, string? toDate = default, string? fromDate = default, System.Threading.CancellationToken cancellationToken = default)
        {
            SandboxValidationUtils.ValidateSandboxMode(_sandboxConfiguration, "GetHistoricalCandleDataWithFromDateAsync");
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatGetHistoricalCandleDataWithFromDate(ref instrumentKey, ref unit, ref interval, ref toDate, ref fromDate);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v3/historical-candle/{instrumentKey}/{unit}/{interval}/{to_date}/{from_date}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/v3/historical-candle/{instrumentKey}/{unit}/{interval}/{to_date}/{from_date}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BinstrumentKey%7D", Uri.EscapeDataString(instrumentKey.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bunit%7D", Uri.EscapeDataString(unit.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Binterval%7D", Uri.EscapeDataString(interval.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bto_date%7D", Uri.EscapeDataString(toDate.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bfrom_date%7D", Uri.EscapeDataString(fromDate.ToString()));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "*/*",
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<GetHistoricalCandleDataWithFromDateApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetHistoricalCandleDataWithFromDateApiResponse>();
                        GetHistoricalCandleDataWithFromDateApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v3/historical-candle/{instrumentKey}/{unit}/{interval}/{to_date}/{from_date}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetHistoricalCandleDataWithFromDateDefaultImplementation(apiResponseLocalVar, instrumentKey, unit, interval, toDate, fromDate);

                        Events.ExecuteOnGetHistoricalCandleDataWithFromDate(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetHistoricalCandleDataWithFromDateDefaultImplementation(e, "/v3/historical-candle/{instrumentKey}/{unit}/{interval}/{to_date}/{from_date}", uriBuilderLocalVar.Path, instrumentKey, unit, interval, toDate, fromDate);
                Events.ExecuteOnErrorGetHistoricalCandleDataWithFromDate(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetHistoricalCandleDataWithFromDateApiResponse"/>
        /// </summary>
        public partial class GetHistoricalCandleDataWithFromDateApiResponse : UpstoxClient.Client.ApiResponse, IGetHistoricalCandleDataWithFromDateApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetHistoricalCandleDataWithFromDateApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetHistoricalCandleDataWithFromDateApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetHistoricalCandleDataWithFromDateApiResponse(ILogger<GetHistoricalCandleDataWithFromDateApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetHistoricalCandleDataWithFromDateApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetHistoricalCandleDataWithFromDateApiResponse(ILogger<GetHistoricalCandleDataWithFromDateApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 405 MethodNotAllowed
            /// </summary>
            /// <returns></returns>
            public bool IsMethodNotAllowed => 405 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 405 MethodNotAllowed
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? MethodNotAllowed()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsMethodNotAllowed
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 405 MethodNotAllowed and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryMethodNotAllowed([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = MethodNotAllowed();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)405);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? TooManyRequests()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 423 Locked
            /// </summary>
            /// <returns></returns>
            public bool IsLocked => 423 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 423 Locked
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? Locked()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsLocked
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 423 Locked and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryLocked([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = Locked();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)423);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? UnprocessableContent()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.GetHistoricalCandleResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.GetHistoricalCandleResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out UpstoxClient.Model.GetHistoricalCandleResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetIntraDayCandleData(ref string? instrumentKey, ref string? unit, ref int? interval);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        private void AfterGetIntraDayCandleDataDefaultImplementation(IGetIntraDayCandleDataApiResponse apiResponseLocalVar, string? instrumentKey, string? unit, int? interval)
        {
            bool suppressDefaultLog = false;
            AfterGetIntraDayCandleData(ref suppressDefaultLog, apiResponseLocalVar, instrumentKey, unit, interval);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        partial void AfterGetIntraDayCandleData(ref bool suppressDefaultLog, IGetIntraDayCandleDataApiResponse apiResponseLocalVar, string? instrumentKey, string? unit, int? interval);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        private void OnErrorGetIntraDayCandleDataDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string? instrumentKey, string? unit, int? interval)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetIntraDayCandleData(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, instrumentKey, unit, interval);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        partial void OnErrorGetIntraDayCandleData(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string? instrumentKey, string? unit, int? interval);

        /// <summary>
        /// Intra day candle data Get OHLC values for all instruments for the present trading day
        /// </summary>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetIntraDayCandleDataApiResponse"/>&gt;</returns>
        public async Task<IGetIntraDayCandleDataApiResponse?> GetIntraDayCandleDataOrDefaultAsync(string? instrumentKey = default, string? unit = default, int? interval = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetIntraDayCandleDataAsync(instrumentKey, unit, interval, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Intra day candle data Get OHLC values for all instruments for the present trading day
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="instrumentKey"></param>
        /// <param name="unit"></param>
        /// <param name="interval"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetIntraDayCandleDataApiResponse"/>&gt;</returns>
        public async Task<IGetIntraDayCandleDataApiResponse> GetIntraDayCandleDataAsync(string? instrumentKey = default, string? unit = default, int? interval = default, System.Threading.CancellationToken cancellationToken = default)
        {
            SandboxValidationUtils.ValidateSandboxMode(_sandboxConfiguration, "GetIntraDayCandleDataAsync");
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatGetIntraDayCandleData(ref instrumentKey, ref unit, ref interval);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v3/historical-candle/intraday/{instrumentKey}/{unit}/{interval}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/v3/historical-candle/intraday/{instrumentKey}/{unit}/{interval}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BinstrumentKey%7D", Uri.EscapeDataString(instrumentKey.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bunit%7D", Uri.EscapeDataString(unit.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Binterval%7D", Uri.EscapeDataString(interval.ToString()));

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "*/*",
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<GetIntraDayCandleDataApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetIntraDayCandleDataApiResponse>();
                        GetIntraDayCandleDataApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v3/historical-candle/intraday/{instrumentKey}/{unit}/{interval}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterGetIntraDayCandleDataDefaultImplementation(apiResponseLocalVar, instrumentKey, unit, interval);

                        Events.ExecuteOnGetIntraDayCandleData(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetIntraDayCandleDataDefaultImplementation(e, "/v3/historical-candle/intraday/{instrumentKey}/{unit}/{interval}", uriBuilderLocalVar.Path, instrumentKey, unit, interval);
                Events.ExecuteOnErrorGetIntraDayCandleData(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetIntraDayCandleDataApiResponse"/>
        /// </summary>
        public partial class GetIntraDayCandleDataApiResponse : UpstoxClient.Client.ApiResponse, IGetIntraDayCandleDataApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetIntraDayCandleDataApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetIntraDayCandleDataApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetIntraDayCandleDataApiResponse(ILogger<GetIntraDayCandleDataApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="GetIntraDayCandleDataApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetIntraDayCandleDataApiResponse(ILogger<GetIntraDayCandleDataApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 405 MethodNotAllowed
            /// </summary>
            /// <returns></returns>
            public bool IsMethodNotAllowed => 405 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 405 MethodNotAllowed
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? MethodNotAllowed()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsMethodNotAllowed
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 405 MethodNotAllowed and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryMethodNotAllowed([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = MethodNotAllowed();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)405);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? TooManyRequests()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 423 Locked
            /// </summary>
            /// <returns></returns>
            public bool IsLocked => 423 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 423 Locked
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? Locked()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsLocked
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 423 Locked and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryLocked([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = Locked();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)423);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? UnprocessableContent()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.GetIntraDayCandleResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.GetIntraDayCandleResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out UpstoxClient.Model.GetIntraDayCandleResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
