// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using UpstoxClient.Client;
using UpstoxClient.Model;
using System.Diagnostics.CodeAnalysis;

namespace UpstoxClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IInstrumentsApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        InstrumentsApiEvents Events { get; }

        /// <summary>
        /// Search instruments
        /// </summary>
        /// <remarks>
        /// This API provides the functionality to retrieve the instrument details for searched query
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">natural language query</param>
        /// <param name="exchanges">Comma separated exchanges (optional)</param>
        /// <param name="segments">Comma separated segments (optional)</param>
        /// <param name="instrumentTypes">Comma separated instrument types (optional)</param>
        /// <param name="expiry">expiry in format: yyyy-MM-dd (optional)</param>
        /// <param name="atmOffset">page number greater than or equal to 1 (optional)</param>
        /// <param name="pageNumber">ATM offset number for queries like ATM, ATM+1, ATM-1, etc. (optional, default to 1)</param>
        /// <param name="records">no of records in a single page (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISearchInstrumentApiResponse"/>&gt;</returns>
        Task<ISearchInstrumentApiResponse> SearchInstrumentAsync(string? query = default, Option<string?> exchanges = default, Option<string?> segments = default, Option<string?> instrumentTypes = default, Option<string?> expiry = default, Option<int?> atmOffset = default, Option<int?> pageNumber = default, Option<int?> records = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Search instruments
        /// </summary>
        /// <remarks>
        /// This API provides the functionality to retrieve the instrument details for searched query
        /// </remarks>
        /// <param name="query">natural language query</param>
        /// <param name="exchanges">Comma separated exchanges (optional)</param>
        /// <param name="segments">Comma separated segments (optional)</param>
        /// <param name="instrumentTypes">Comma separated instrument types (optional)</param>
        /// <param name="expiry">expiry in format: yyyy-MM-dd (optional)</param>
        /// <param name="atmOffset">page number greater than or equal to 1 (optional)</param>
        /// <param name="pageNumber">ATM offset number for queries like ATM, ATM+1, ATM-1, etc. (optional, default to 1)</param>
        /// <param name="records">no of records in a single page (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISearchInstrumentApiResponse"/>?&gt;</returns>
        Task<ISearchInstrumentApiResponse?> SearchInstrumentOrDefaultAsync(string? query = default, Option<string?> exchanges = default, Option<string?> segments = default, Option<string?> instrumentTypes = default, Option<string?> expiry = default, Option<int?> atmOffset = default, Option<int?> pageNumber = default, Option<int?> records = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ISearchInstrumentApiResponse"/>
    /// </summary>
    public interface ISearchInstrumentApiResponse : UpstoxClient.Client.IApiResponse, IMethodNotAllowed<UpstoxClient.Model.ApiGatewayErrorResponse?>, IBadRequest<UpstoxClient.Model.ApiGatewayErrorResponse?>, IInternalServerError<UpstoxClient.Model.ApiGatewayErrorResponse?>, ILocked<UpstoxClient.Model.ApiGatewayErrorResponse?>, IUnprocessableContent<UpstoxClient.Model.ApiGatewayErrorResponse?>, ITooManyRequests<UpstoxClient.Model.ApiGatewayErrorResponse?>, IOk<UpstoxClient.Model.SearchInstrumentResponse?>
    {
        /// <summary>
        /// Returns true if the response is 405 MethodNotAllowed
        /// </summary>
        /// <returns></returns>
        bool IsMethodNotAllowed { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }

        /// <summary>
        /// Returns true if the response is 423 Locked
        /// </summary>
        /// <returns></returns>
        bool IsLocked { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }

        /// <summary>
        /// Returns true if the response is 429 TooManyRequests
        /// </summary>
        /// <returns></returns>
        bool IsTooManyRequests { get; }

        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class InstrumentsApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnSearchInstrument;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorSearchInstrument;

        internal void ExecuteOnSearchInstrument(InstrumentsApi.SearchInstrumentApiResponse apiResponse)
        {
            OnSearchInstrument?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorSearchInstrument(Exception exception)
        {
            OnErrorSearchInstrument?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class InstrumentsApi : IInstrumentsApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<InstrumentsApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public InstrumentsApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="OauthTokenProvider"/>
        /// </summary>
        public TokenProvider<OAuthToken> OauthTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="InstrumentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public InstrumentsApi(ILogger<InstrumentsApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, InstrumentsApiEvents instrumentsApiEvents,
            TokenProvider<OAuthToken> oauthTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<InstrumentsApi>();
            HttpClient = httpClient;
            Events = instrumentsApiEvents;
            OauthTokenProvider = oauthTokenProvider;
        }

        partial void FormatSearchInstrument(ref string? query, ref Option<string?> exchanges, ref Option<string?> segments, ref Option<string?> instrumentTypes, ref Option<string?> expiry, ref Option<int?> atmOffset, ref Option<int?> pageNumber, ref Option<int?> records);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="query"></param>
        /// <param name="exchanges"></param>
        /// <param name="segments"></param>
        /// <param name="instrumentTypes"></param>
        /// <param name="expiry"></param>
        /// <param name="atmOffset"></param>
        /// <param name="pageNumber"></param>
        /// <param name="records"></param>
        private void AfterSearchInstrumentDefaultImplementation(ISearchInstrumentApiResponse apiResponseLocalVar, string? query, Option<string?> exchanges, Option<string?> segments, Option<string?> instrumentTypes, Option<string?> expiry, Option<int?> atmOffset, Option<int?> pageNumber, Option<int?> records)
        {
            bool suppressDefaultLog = false;
            AfterSearchInstrument(ref suppressDefaultLog, apiResponseLocalVar, query, exchanges, segments, instrumentTypes, expiry, atmOffset, pageNumber, records);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="query"></param>
        /// <param name="exchanges"></param>
        /// <param name="segments"></param>
        /// <param name="instrumentTypes"></param>
        /// <param name="expiry"></param>
        /// <param name="atmOffset"></param>
        /// <param name="pageNumber"></param>
        /// <param name="records"></param>
        partial void AfterSearchInstrument(ref bool suppressDefaultLog, ISearchInstrumentApiResponse apiResponseLocalVar, string? query, Option<string?> exchanges, Option<string?> segments, Option<string?> instrumentTypes, Option<string?> expiry, Option<int?> atmOffset, Option<int?> pageNumber, Option<int?> records);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="query"></param>
        /// <param name="exchanges"></param>
        /// <param name="segments"></param>
        /// <param name="instrumentTypes"></param>
        /// <param name="expiry"></param>
        /// <param name="atmOffset"></param>
        /// <param name="pageNumber"></param>
        /// <param name="records"></param>
        private void OnErrorSearchInstrumentDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string? query, Option<string?> exchanges, Option<string?> segments, Option<string?> instrumentTypes, Option<string?> expiry, Option<int?> atmOffset, Option<int?> pageNumber, Option<int?> records)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorSearchInstrument(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, query, exchanges, segments, instrumentTypes, expiry, atmOffset, pageNumber, records);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="query"></param>
        /// <param name="exchanges"></param>
        /// <param name="segments"></param>
        /// <param name="instrumentTypes"></param>
        /// <param name="expiry"></param>
        /// <param name="atmOffset"></param>
        /// <param name="pageNumber"></param>
        /// <param name="records"></param>
        partial void OnErrorSearchInstrument(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string? query, Option<string?> exchanges, Option<string?> segments, Option<string?> instrumentTypes, Option<string?> expiry, Option<int?> atmOffset, Option<int?> pageNumber, Option<int?> records);

        /// <summary>
        /// Search instruments This API provides the functionality to retrieve the instrument details for searched query
        /// </summary>
        /// <param name="query">natural language query</param>
        /// <param name="exchanges">Comma separated exchanges (optional)</param>
        /// <param name="segments">Comma separated segments (optional)</param>
        /// <param name="instrumentTypes">Comma separated instrument types (optional)</param>
        /// <param name="expiry">expiry in format: yyyy-MM-dd (optional)</param>
        /// <param name="atmOffset">page number greater than or equal to 1 (optional)</param>
        /// <param name="pageNumber">ATM offset number for queries like ATM, ATM+1, ATM-1, etc. (optional, default to 1)</param>
        /// <param name="records">no of records in a single page (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISearchInstrumentApiResponse"/>&gt;</returns>
        public async Task<ISearchInstrumentApiResponse?> SearchInstrumentOrDefaultAsync(string? query = default, Option<string?> exchanges = default, Option<string?> segments = default, Option<string?> instrumentTypes = default, Option<string?> expiry = default, Option<int?> atmOffset = default, Option<int?> pageNumber = default, Option<int?> records = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await SearchInstrumentAsync(query, exchanges, segments, instrumentTypes, expiry, atmOffset, pageNumber, records, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Search instruments This API provides the functionality to retrieve the instrument details for searched query
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="query">natural language query</param>
        /// <param name="exchanges">Comma separated exchanges (optional)</param>
        /// <param name="segments">Comma separated segments (optional)</param>
        /// <param name="instrumentTypes">Comma separated instrument types (optional)</param>
        /// <param name="expiry">expiry in format: yyyy-MM-dd (optional)</param>
        /// <param name="atmOffset">page number greater than or equal to 1 (optional)</param>
        /// <param name="pageNumber">ATM offset number for queries like ATM, ATM+1, ATM-1, etc. (optional, default to 1)</param>
        /// <param name="records">no of records in a single page (optional, default to 10)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISearchInstrumentApiResponse"/>&gt;</returns>
        public async Task<ISearchInstrumentApiResponse> SearchInstrumentAsync(string? query = default, Option<string?> exchanges = default, Option<string?> segments = default, Option<string?> instrumentTypes = default, Option<string?> expiry = default, Option<int?> atmOffset = default, Option<int?> pageNumber = default, Option<int?> records = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatSearchInstrument(ref query, ref exchanges, ref segments, ref instrumentTypes, ref expiry, ref atmOffset, ref pageNumber, ref records);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v2/instruments/search"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v2/instruments/search");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["query"] = ClientUtils.ParameterToString(query);

                    if (exchanges.IsSet)
                        parseQueryStringLocalVar["exchanges"] = ClientUtils.ParameterToString(exchanges.Value);

                    if (segments.IsSet)
                        parseQueryStringLocalVar["segments"] = ClientUtils.ParameterToString(segments.Value);

                    if (instrumentTypes.IsSet)
                        parseQueryStringLocalVar["instrument_types"] = ClientUtils.ParameterToString(instrumentTypes.Value);

                    if (expiry.IsSet)
                        parseQueryStringLocalVar["expiry"] = ClientUtils.ParameterToString(expiry.Value);

                    if (atmOffset.IsSet)
                        parseQueryStringLocalVar["atm_offset"] = ClientUtils.ParameterToString(atmOffset.Value);

                    if (pageNumber.IsSet)
                        parseQueryStringLocalVar["page_number"] = ClientUtils.ParameterToString(pageNumber.Value);

                    if (records.IsSet)
                        parseQueryStringLocalVar["records"] = ClientUtils.ParameterToString(records.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    OAuthToken oauthTokenLocalVar1 = (OAuthToken) await OauthTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(oauthTokenLocalVar1);

                    oauthTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "*/*",
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<SearchInstrumentApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<SearchInstrumentApiResponse>();
                        SearchInstrumentApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v2/instruments/search", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterSearchInstrumentDefaultImplementation(apiResponseLocalVar, query, exchanges, segments, instrumentTypes, expiry, atmOffset, pageNumber, records);

                        Events.ExecuteOnSearchInstrument(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorSearchInstrumentDefaultImplementation(e, "/v2/instruments/search", uriBuilderLocalVar.Path, query, exchanges, segments, instrumentTypes, expiry, atmOffset, pageNumber, records);
                Events.ExecuteOnErrorSearchInstrument(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="SearchInstrumentApiResponse"/>
        /// </summary>
        public partial class SearchInstrumentApiResponse : UpstoxClient.Client.ApiResponse, ISearchInstrumentApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<SearchInstrumentApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="SearchInstrumentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public SearchInstrumentApiResponse(ILogger<SearchInstrumentApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="SearchInstrumentApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public SearchInstrumentApiResponse(ILogger<SearchInstrumentApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 405 MethodNotAllowed
            /// </summary>
            /// <returns></returns>
            public bool IsMethodNotAllowed => 405 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 405 MethodNotAllowed
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? MethodNotAllowed()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsMethodNotAllowed
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 405 MethodNotAllowed and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryMethodNotAllowed([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = MethodNotAllowed();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)405);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 423 Locked
            /// </summary>
            /// <returns></returns>
            public bool IsLocked => 423 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 423 Locked
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? Locked()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsLocked
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 423 Locked and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryLocked([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = Locked();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)423);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? UnprocessableContent()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnprocessableContent
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnprocessableContent([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = UnprocessableContent();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)422);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public bool IsTooManyRequests => 429 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 429 TooManyRequests
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.ApiGatewayErrorResponse? TooManyRequests()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsTooManyRequests
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.ApiGatewayErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 429 TooManyRequests and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryTooManyRequests([NotNullWhen(true)]out UpstoxClient.Model.ApiGatewayErrorResponse? result)
            {
                result = null;

                try
                {
                    result = TooManyRequests();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)429);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public UpstoxClient.Model.SearchInstrumentResponse? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<UpstoxClient.Model.SearchInstrumentResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out UpstoxClient.Model.SearchInstrumentResponse? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
