/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using UpstoxClient.Model;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("UpstoxClient.Test")]

namespace UpstoxClient.Client
{
    /// <summary>
    /// Utility functions providing some benefit to API client consumers.
    /// </summary>
    public static partial class ClientUtils
    {

        /// <summary>
        /// A delegate for events.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        /// <returns></returns>
        public delegate void EventHandler<T>(object sender, T e) where T : EventArgs;

        /// <summary>
        /// Returns true when deserialization succeeds.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="json"></param>
        /// <param name="options"></param>
        /// <param name="result"></param>
        /// <returns></returns>
        public static bool TryDeserialize<T>(string json, JsonSerializerOptions options, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? result)
        {
            try
            {
                result = JsonSerializer.Deserialize<T>(json, options);
                return result != null;
            }
            catch (Exception)
            {
                result = default;
                return false;
            }
        }

        /// <summary>
        /// Returns true when deserialization succeeds.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="reader"></param>
        /// <param name="options"></param>
        /// <param name="result"></param>
        /// <returns></returns>
        public static bool TryDeserialize<T>(ref Utf8JsonReader reader, JsonSerializerOptions options, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out T? result)
        {
            try
            {
                result = JsonSerializer.Deserialize<T>(ref reader, options);
                return result != null;
            }
            catch (Exception)
            {
                result = default;
                return false;
            }
        }

        /// <summary>
        /// If parameter is DateTime, output in a formatted string (default ISO 8601), customizable with Configuration.DateTime.
        /// If parameter is a list, join the list with ",".
        /// Otherwise just return the string.
        /// </summary>
        /// <param name="obj">The parameter (header, path, query, form).</param>
        /// <param name="format">The DateTime serialization format.</param>
        /// <returns>Formatted string.</returns>
        public static string? ParameterToString(object? obj, string? format = ISO8601_DATETIME_FORMAT)
        {
            if (obj is DateTime dateTime)
                // Return a formatted date string - Can be customized with Configuration.DateTimeFormat
                // Defaults to an ISO 8601, using the known as a Round-trip date/time pattern ("o")
                // https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8
                // For example: 2009-06-15T13:45:30.0000000
                return dateTime.ToString(format);
            if (obj is DateTimeOffset dateTimeOffset)
                // Return a formatted date string - Can be customized with Configuration.DateTimeFormat
                // Defaults to an ISO 8601, using the known as a Round-trip date/time pattern ("o")
                // https://msdn.microsoft.com/en-us/library/az4se3k1(v=vs.110).aspx#Anchor_8
                // For example: 2009-06-15T13:45:30.0000000
                return dateTimeOffset.ToString(format);
            if (obj is DateOnly dateOnly)
                return dateOnly.ToString(format);
            if (obj is bool boolean)
                return boolean
                    ? "true"
                    : "false";
            if (obj is ApiGatewayErrorResponse.StatusEnum apiGatewayErrorResponseStatusEnum)
                return ApiGatewayErrorResponse.StatusEnumToJsonValue(apiGatewayErrorResponseStatusEnum);
            if (obj is CancelOrExitMultiOrderResponse.StatusEnum cancelOrExitMultiOrderResponseStatusEnum)
                return CancelOrExitMultiOrderResponse.StatusEnumToJsonValue(cancelOrExitMultiOrderResponseStatusEnum);
            if (obj is CancelOrderResponse.StatusEnum cancelOrderResponseStatusEnum)
                return CancelOrderResponse.StatusEnumToJsonValue(cancelOrderResponseStatusEnum);
            if (obj is CancelOrderV3Response.StatusEnum cancelOrderV3ResponseStatusEnum)
                return CancelOrderV3Response.StatusEnumToJsonValue(cancelOrderV3ResponseStatusEnum);
            if (obj is ConvertPositionRequest.NewProductEnum convertPositionRequestNewProductEnum)
                return ConvertPositionRequest.NewProductEnumToJsonValue(convertPositionRequestNewProductEnum);
            if (obj is ConvertPositionRequest.OldProductEnum convertPositionRequestOldProductEnum)
                return ConvertPositionRequest.OldProductEnumToJsonValue(convertPositionRequestOldProductEnum);
            if (obj is ConvertPositionRequest.TransactionTypeEnum convertPositionRequestTransactionTypeEnum)
                return ConvertPositionRequest.TransactionTypeEnumToJsonValue(convertPositionRequestTransactionTypeEnum);
            if (obj is ConvertPositionResponse.StatusEnum convertPositionResponseStatusEnum)
                return ConvertPositionResponse.StatusEnumToJsonValue(convertPositionResponseStatusEnum);
            if (obj is GetBrokerageResponse.StatusEnum getBrokerageResponseStatusEnum)
                return GetBrokerageResponse.StatusEnumToJsonValue(getBrokerageResponseStatusEnum);
            if (obj is GetExchangeTimingResponse.StatusEnum getExchangeTimingResponseStatusEnum)
                return GetExchangeTimingResponse.StatusEnumToJsonValue(getExchangeTimingResponseStatusEnum);
            if (obj is GetExpiredFuturesContractResponse.StatusEnum getExpiredFuturesContractResponseStatusEnum)
                return GetExpiredFuturesContractResponse.StatusEnumToJsonValue(getExpiredFuturesContractResponseStatusEnum);
            if (obj is GetExpiriesResponse.StatusEnum getExpiriesResponseStatusEnum)
                return GetExpiriesResponse.StatusEnumToJsonValue(getExpiriesResponseStatusEnum);
            if (obj is GetFullMarketQuoteResponse.StatusEnum getFullMarketQuoteResponseStatusEnum)
                return GetFullMarketQuoteResponse.StatusEnumToJsonValue(getFullMarketQuoteResponseStatusEnum);
            if (obj is GetGttOrderResponse.StatusEnum getGttOrderResponseStatusEnum)
                return GetGttOrderResponse.StatusEnumToJsonValue(getGttOrderResponseStatusEnum);
            if (obj is GetHistoricalCandleResponse.StatusEnum getHistoricalCandleResponseStatusEnum)
                return GetHistoricalCandleResponse.StatusEnumToJsonValue(getHistoricalCandleResponseStatusEnum);
            if (obj is GetHoldingsResponse.StatusEnum getHoldingsResponseStatusEnum)
                return GetHoldingsResponse.StatusEnumToJsonValue(getHoldingsResponseStatusEnum);
            if (obj is GetHolidayResponse.StatusEnum getHolidayResponseStatusEnum)
                return GetHolidayResponse.StatusEnumToJsonValue(getHolidayResponseStatusEnum);
            if (obj is GetIntraDayCandleResponse.StatusEnum getIntraDayCandleResponseStatusEnum)
                return GetIntraDayCandleResponse.StatusEnumToJsonValue(getIntraDayCandleResponseStatusEnum);
            if (obj is GetMarketQuoteLastTradedPriceResponse.StatusEnum getMarketQuoteLastTradedPriceResponseStatusEnum)
                return GetMarketQuoteLastTradedPriceResponse.StatusEnumToJsonValue(getMarketQuoteLastTradedPriceResponseStatusEnum);
            if (obj is GetMarketQuoteLastTradedPriceResponseV3.StatusEnum getMarketQuoteLastTradedPriceResponseV3StatusEnum)
                return GetMarketQuoteLastTradedPriceResponseV3.StatusEnumToJsonValue(getMarketQuoteLastTradedPriceResponseV3StatusEnum);
            if (obj is GetMarketQuoteOHLCResponse.StatusEnum getMarketQuoteOHLCResponseStatusEnum)
                return GetMarketQuoteOHLCResponse.StatusEnumToJsonValue(getMarketQuoteOHLCResponseStatusEnum);
            if (obj is GetMarketQuoteOHLCResponseV3.StatusEnum getMarketQuoteOHLCResponseV3StatusEnum)
                return GetMarketQuoteOHLCResponseV3.StatusEnumToJsonValue(getMarketQuoteOHLCResponseV3StatusEnum);
            if (obj is GetMarketQuoteOptionGreekResponseV3.StatusEnum getMarketQuoteOptionGreekResponseV3StatusEnum)
                return GetMarketQuoteOptionGreekResponseV3.StatusEnumToJsonValue(getMarketQuoteOptionGreekResponseV3StatusEnum);
            if (obj is GetMarketStatusResponse.StatusEnum getMarketStatusResponseStatusEnum)
                return GetMarketStatusResponse.StatusEnumToJsonValue(getMarketStatusResponseStatusEnum);
            if (obj is GetOptionChainResponse.StatusEnum getOptionChainResponseStatusEnum)
                return GetOptionChainResponse.StatusEnumToJsonValue(getOptionChainResponseStatusEnum);
            if (obj is GetOptionContractResponse.StatusEnum getOptionContractResponseStatusEnum)
                return GetOptionContractResponse.StatusEnumToJsonValue(getOptionContractResponseStatusEnum);
            if (obj is GetOrderBookResponse.StatusEnum getOrderBookResponseStatusEnum)
                return GetOrderBookResponse.StatusEnumToJsonValue(getOrderBookResponseStatusEnum);
            if (obj is GetOrderDetailsResponse.StatusEnum getOrderDetailsResponseStatusEnum)
                return GetOrderDetailsResponse.StatusEnumToJsonValue(getOrderDetailsResponseStatusEnum);
            if (obj is GetOrderResponse.StatusEnum getOrderResponseStatusEnum)
                return GetOrderResponse.StatusEnumToJsonValue(getOrderResponseStatusEnum);
            if (obj is GetPositionResponse.StatusEnum getPositionResponseStatusEnum)
                return GetPositionResponse.StatusEnumToJsonValue(getPositionResponseStatusEnum);
            if (obj is GetProfileResponse.StatusEnum getProfileResponseStatusEnum)
                return GetProfileResponse.StatusEnumToJsonValue(getProfileResponseStatusEnum);
            if (obj is GetProfitAndLossChargesResponse.StatusEnum getProfitAndLossChargesResponseStatusEnum)
                return GetProfitAndLossChargesResponse.StatusEnumToJsonValue(getProfitAndLossChargesResponseStatusEnum);
            if (obj is GetTradeResponse.StatusEnum getTradeResponseStatusEnum)
                return GetTradeResponse.StatusEnumToJsonValue(getTradeResponseStatusEnum);
            if (obj is GetTradeWiseProfitAndLossDataResponse.StatusEnum getTradeWiseProfitAndLossDataResponseStatusEnum)
                return GetTradeWiseProfitAndLossDataResponse.StatusEnumToJsonValue(getTradeWiseProfitAndLossDataResponseStatusEnum);
            if (obj is GetTradeWiseProfitAndLossMetaDataResponse.StatusEnum getTradeWiseProfitAndLossMetaDataResponseStatusEnum)
                return GetTradeWiseProfitAndLossMetaDataResponse.StatusEnumToJsonValue(getTradeWiseProfitAndLossMetaDataResponseStatusEnum);
            if (obj is GetUserFundMarginResponse.StatusEnum getUserFundMarginResponseStatusEnum)
                return GetUserFundMarginResponse.StatusEnumToJsonValue(getUserFundMarginResponseStatusEnum);
            if (obj is GttModifyOrderRequest.TypeEnum gttModifyOrderRequestTypeEnum)
                return GttModifyOrderRequest.TypeEnumToJsonValue(gttModifyOrderRequestTypeEnum);
            if (obj is GttPlaceOrderRequest.TypeEnum gttPlaceOrderRequestTypeEnum)
                return GttPlaceOrderRequest.TypeEnumToJsonValue(gttPlaceOrderRequestTypeEnum);
            if (obj is GttPlaceOrderRequest.ProductEnum gttPlaceOrderRequestProductEnum)
                return GttPlaceOrderRequest.ProductEnumToJsonValue(gttPlaceOrderRequestProductEnum);
            if (obj is GttPlaceOrderRequest.TransactionTypeEnum gttPlaceOrderRequestTransactionTypeEnum)
                return GttPlaceOrderRequest.TransactionTypeEnumToJsonValue(gttPlaceOrderRequestTransactionTypeEnum);
            if (obj is GttRule.StrategyEnum gttRuleStrategyEnum)
                return GttRule.StrategyEnumToJsonValue(gttRuleStrategyEnum);
            if (obj is GttRule.TriggerTypeEnum gttRuleTriggerTypeEnum)
                return GttRule.TriggerTypeEnumToJsonValue(gttRuleTriggerTypeEnum);
            if (obj is GttTriggerOrderResponse.StatusEnum gttTriggerOrderResponseStatusEnum)
                return GttTriggerOrderResponse.StatusEnumToJsonValue(gttTriggerOrderResponseStatusEnum);
            if (obj is HoldingsData.ExchangeEnum holdingsDataExchangeEnum)
                return HoldingsData.ExchangeEnumToJsonValue(holdingsDataExchangeEnum);
            if (obj is HolidayData.HolidayTypeEnum holidayDataHolidayTypeEnum)
                return HolidayData.HolidayTypeEnumToJsonValue(holidayDataHolidayTypeEnum);
            if (obj is IndieUserInitTokenResponse.StatusEnum indieUserInitTokenResponseStatusEnum)
                return IndieUserInitTokenResponse.StatusEnumToJsonValue(indieUserInitTokenResponseStatusEnum);
            if (obj is LogoutResponse.StatusEnum logoutResponseStatusEnum)
                return LogoutResponse.StatusEnumToJsonValue(logoutResponseStatusEnum);
            if (obj is ModifyOrderRequest.ValidityEnum modifyOrderRequestValidityEnum)
                return ModifyOrderRequest.ValidityEnumToJsonValue(modifyOrderRequestValidityEnum);
            if (obj is ModifyOrderRequest.OrderTypeEnum modifyOrderRequestOrderTypeEnum)
                return ModifyOrderRequest.OrderTypeEnumToJsonValue(modifyOrderRequestOrderTypeEnum);
            if (obj is ModifyOrderResponse.StatusEnum modifyOrderResponseStatusEnum)
                return ModifyOrderResponse.StatusEnumToJsonValue(modifyOrderResponseStatusEnum);
            if (obj is ModifyOrderV3Response.StatusEnum modifyOrderV3ResponseStatusEnum)
                return ModifyOrderV3Response.StatusEnumToJsonValue(modifyOrderV3ResponseStatusEnum);
            if (obj is MultiOrderRequest.ProductEnum multiOrderRequestProductEnum)
                return MultiOrderRequest.ProductEnumToJsonValue(multiOrderRequestProductEnum);
            if (obj is MultiOrderRequest.ValidityEnum multiOrderRequestValidityEnum)
                return MultiOrderRequest.ValidityEnumToJsonValue(multiOrderRequestValidityEnum);
            if (obj is MultiOrderRequest.OrderTypeEnum multiOrderRequestOrderTypeEnum)
                return MultiOrderRequest.OrderTypeEnumToJsonValue(multiOrderRequestOrderTypeEnum);
            if (obj is MultiOrderRequest.TransactionTypeEnum multiOrderRequestTransactionTypeEnum)
                return MultiOrderRequest.TransactionTypeEnumToJsonValue(multiOrderRequestTransactionTypeEnum);
            if (obj is MultiOrderResponse.StatusEnum multiOrderResponseStatusEnum)
                return MultiOrderResponse.StatusEnumToJsonValue(multiOrderResponseStatusEnum);
            if (obj is OrderBookData.ExchangeEnum orderBookDataExchangeEnum)
                return OrderBookData.ExchangeEnumToJsonValue(orderBookDataExchangeEnum);
            if (obj is OrderBookData.ProductEnum orderBookDataProductEnum)
                return OrderBookData.ProductEnumToJsonValue(orderBookDataProductEnum);
            if (obj is OrderBookData.OrderTypeEnum orderBookDataOrderTypeEnum)
                return OrderBookData.OrderTypeEnumToJsonValue(orderBookDataOrderTypeEnum);
            if (obj is OrderBookData.ValidityEnum orderBookDataValidityEnum)
                return OrderBookData.ValidityEnumToJsonValue(orderBookDataValidityEnum);
            if (obj is OrderBookData.TransactionTypeEnum orderBookDataTransactionTypeEnum)
                return OrderBookData.TransactionTypeEnumToJsonValue(orderBookDataTransactionTypeEnum);
            if (obj is OrderData.ExchangeEnum orderDataExchangeEnum)
                return OrderData.ExchangeEnumToJsonValue(orderDataExchangeEnum);
            if (obj is OrderData.ProductEnum orderDataProductEnum)
                return OrderData.ProductEnumToJsonValue(orderDataProductEnum);
            if (obj is OrderData.ValidityEnum orderDataValidityEnum)
                return OrderData.ValidityEnumToJsonValue(orderDataValidityEnum);
            if (obj is OrderData.OrderTypeEnum orderDataOrderTypeEnum)
                return OrderData.OrderTypeEnumToJsonValue(orderDataOrderTypeEnum);
            if (obj is OrderData.TransactionTypeEnum orderDataTransactionTypeEnum)
                return OrderData.TransactionTypeEnumToJsonValue(orderDataTransactionTypeEnum);
            if (obj is PlaceOrderRequest.ProductEnum placeOrderRequestProductEnum)
                return PlaceOrderRequest.ProductEnumToJsonValue(placeOrderRequestProductEnum);
            if (obj is PlaceOrderRequest.ValidityEnum placeOrderRequestValidityEnum)
                return PlaceOrderRequest.ValidityEnumToJsonValue(placeOrderRequestValidityEnum);
            if (obj is PlaceOrderRequest.OrderTypeEnum placeOrderRequestOrderTypeEnum)
                return PlaceOrderRequest.OrderTypeEnumToJsonValue(placeOrderRequestOrderTypeEnum);
            if (obj is PlaceOrderRequest.TransactionTypeEnum placeOrderRequestTransactionTypeEnum)
                return PlaceOrderRequest.TransactionTypeEnumToJsonValue(placeOrderRequestTransactionTypeEnum);
            if (obj is PlaceOrderResponse.StatusEnum placeOrderResponseStatusEnum)
                return PlaceOrderResponse.StatusEnumToJsonValue(placeOrderResponseStatusEnum);
            if (obj is PlaceOrderV3Request.ProductEnum placeOrderV3RequestProductEnum)
                return PlaceOrderV3Request.ProductEnumToJsonValue(placeOrderV3RequestProductEnum);
            if (obj is PlaceOrderV3Request.ValidityEnum placeOrderV3RequestValidityEnum)
                return PlaceOrderV3Request.ValidityEnumToJsonValue(placeOrderV3RequestValidityEnum);
            if (obj is PlaceOrderV3Request.OrderTypeEnum placeOrderV3RequestOrderTypeEnum)
                return PlaceOrderV3Request.OrderTypeEnumToJsonValue(placeOrderV3RequestOrderTypeEnum);
            if (obj is PlaceOrderV3Request.TransactionTypeEnum placeOrderV3RequestTransactionTypeEnum)
                return PlaceOrderV3Request.TransactionTypeEnumToJsonValue(placeOrderV3RequestTransactionTypeEnum);
            if (obj is PlaceOrderV3Response.StatusEnum placeOrderV3ResponseStatusEnum)
                return PlaceOrderV3Response.StatusEnumToJsonValue(placeOrderV3ResponseStatusEnum);
            if (obj is PositionData.ExchangeEnum positionDataExchangeEnum)
                return PositionData.ExchangeEnumToJsonValue(positionDataExchangeEnum);
            if (obj is PostMarginResponse.StatusEnum postMarginResponseStatusEnum)
                return PostMarginResponse.StatusEnumToJsonValue(postMarginResponseStatusEnum);
            if (obj is ProfileData.ExchangesEnum profileDataExchangesEnum)
                return ProfileData.ExchangesEnumToJsonValue(profileDataExchangesEnum);
            if (obj is ProfileData.ProductsEnum profileDataProductsEnum)
                return ProfileData.ProductsEnumToJsonValue(profileDataProductsEnum);
            if (obj is ProfileData.OrderTypesEnum profileDataOrderTypesEnum)
                return ProfileData.OrderTypesEnumToJsonValue(profileDataOrderTypesEnum);
            if (obj is TokenResponse.ExchangesEnum tokenResponseExchangesEnum)
                return TokenResponse.ExchangesEnumToJsonValue(tokenResponseExchangesEnum);
            if (obj is TokenResponse.ProductsEnum tokenResponseProductsEnum)
                return TokenResponse.ProductsEnumToJsonValue(tokenResponseProductsEnum);
            if (obj is TokenResponse.OrderTypesEnum tokenResponseOrderTypesEnum)
                return TokenResponse.OrderTypesEnumToJsonValue(tokenResponseOrderTypesEnum);
            if (obj is TradeData.ExchangeEnum tradeDataExchangeEnum)
                return TradeData.ExchangeEnumToJsonValue(tradeDataExchangeEnum);
            if (obj is TradeData.ProductEnum tradeDataProductEnum)
                return TradeData.ProductEnumToJsonValue(tradeDataProductEnum);
            if (obj is TradeData.OrderTypeEnum tradeDataOrderTypeEnum)
                return TradeData.OrderTypeEnumToJsonValue(tradeDataOrderTypeEnum);
            if (obj is TradeData.TransactionTypeEnum tradeDataTransactionTypeEnum)
                return TradeData.TransactionTypeEnumToJsonValue(tradeDataTransactionTypeEnum);
            if (obj is TradeHistoryResponse.StatusEnum tradeHistoryResponseStatusEnum)
                return TradeHistoryResponse.StatusEnumToJsonValue(tradeHistoryResponseStatusEnum);
            if (obj is WebsocketAuthRedirectResponse.StatusEnum websocketAuthRedirectResponseStatusEnum)
                return WebsocketAuthRedirectResponse.StatusEnumToJsonValue(websocketAuthRedirectResponseStatusEnum);
            if (obj is ICollection collection)
            {
                List<string?> entries = new();
                foreach (var entry in collection)
                    entries.Add(ParameterToString(entry));
                return string.Join(",", entries);
            }

            return Convert.ToString(obj, System.Globalization.CultureInfo.InvariantCulture);
        }

        /// <summary>
        /// URL encode a string
        /// Credit/Ref: https://github.com/restsharp/RestSharp/blob/master/RestSharp/Extensions/StringExtensions.cs#L50
        /// </summary>
        /// <param name="input">string to be URL encoded</param>
        /// <returns>Byte array</returns>
        public static string UrlEncode(string input)
        {
            const int maxLength = 32766;

            if (input == null)
            {
                throw new ArgumentNullException("input");
            }

            if (input.Length <= maxLength)
            {
                return Uri.EscapeDataString(input);
            }

            StringBuilder sb = new StringBuilder(input.Length * 2);
            int index = 0;

            while (index < input.Length)
            {
                int length = Math.Min(input.Length - index, maxLength);
                string subString = input.Substring(index, length);

                sb.Append(Uri.EscapeDataString(subString));
                index += subString.Length;
            }

            return sb.ToString();
        }

        /// <summary>
        /// Encode string in base64 format.
        /// </summary>
        /// <param name="text">string to be encoded.</param>
        /// <returns>Encoded string.</returns>
        public static string Base64Encode(string text)
        {
            return Convert.ToBase64String(global::System.Text.Encoding.UTF8.GetBytes(text));
        }

        /// <summary>
        /// Convert stream to byte array
        /// </summary>
        /// <param name="inputStream">Input stream to be converted</param>
        /// <returns>Byte array</returns>
        public static byte[] ReadAsBytes(Stream inputStream)
        {
            using (var ms = new MemoryStream())
            {
                inputStream.CopyTo(ms);
                return ms.ToArray();
            }
        }

        /// <summary>
        /// Select the Content-Type header's value from the given content-type array:
        /// if JSON type exists in the given array, use it;
        /// otherwise use the first one defined in 'consumes'
        /// </summary>
        /// <param name="contentTypes">The Content-Type array to select from.</param>
        /// <returns>The Content-Type header to use.</returns>
        public static string? SelectHeaderContentType(string[] contentTypes)
        {
            if (contentTypes.Length == 0)
                return null;

            foreach (var contentType in contentTypes)
            {
                if (IsJsonMime(contentType))
                    return contentType;
            }

            return contentTypes[0]; // use the first content type specified in 'consumes'
        }

        /// <summary>
        /// Select the Accept header's value from the given accepts array:
        /// if JSON exists in the given array, use it;
        /// otherwise use all of them (joining into a string)
        /// </summary>
        /// <param name="accepts">The accepts array to select from.</param>
        /// <returns>The Accept header to use.</returns>
        public static string? SelectHeaderAccept(string[] accepts)
        {
            if (accepts.Length == 0)
                return null;

            if (accepts.Contains("application/json", StringComparer.OrdinalIgnoreCase))
                return "application/json";

            return string.Join(",", accepts);
        }

        /// <summary>
        /// Provides a case-insensitive check that a provided content type is a known JSON-like content type.
        /// </summary>
        [GeneratedRegex("(?i)^(application/json|[^;/ \t]+/[^;/ \t]+[+]json)[ \t]*(;.*)?$")]
        private static partial Regex JsonRegex();

        /// <summary>
        /// Check if the given MIME is a JSON MIME.
        /// JSON MIME examples:
        ///    application/json
        ///    application/json; charset=UTF8
        ///    APPLICATION/JSON
        ///    application/vnd.company+json
        /// </summary>
        /// <param name="mime">MIME</param>
        /// <returns>Returns True if MIME type is json.</returns>
        public static bool IsJsonMime(string mime)
        {
            if (string.IsNullOrWhiteSpace(mime)) return false;

            return JsonRegex().IsMatch(mime) || mime.Equals("application/json-patch+json");
        }

        /// <summary>
        /// Get the discriminator
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="discriminator"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public static string? GetDiscriminator(Utf8JsonReader utf8JsonReader, string discriminator)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    if (localVarJsonPropertyName != null && localVarJsonPropertyName.Equals(discriminator))
                        return utf8JsonReader.GetString();
                }
            }

            throw new JsonException("The specified discriminator was not found.");
        }

        /// <summary>
        /// The base path of the API
        /// </summary>
        public const string BASE_ADDRESS = "https://api.upstox.com";

        /// <summary>
        /// The scheme of the API
        /// </summary>
        public const string SCHEME = "https";

        /// <summary>
        /// The context path of the API
        /// </summary>
        public const string CONTEXT_PATH = "";

        /// <summary>
        /// The host of the API
        /// </summary>
        public const string HOST = "api.upstox.com";

        /// <summary>
        /// The format to use for DateTime serialization
        /// </summary>
        public const string ISO8601_DATETIME_FORMAT = "o";
    }
}
