/* 
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UpstoxClient.Api;
using UpstoxClient.Model;
using UpstoxClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace UpstoxClient.Test
{
    /// <summary>
    ///  Class for testing ConvertPositionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConvertPositionRequestTests
    {
        // TODO uncomment below to declare an instance variable for ConvertPositionRequest
        //private ConvertPositionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConvertPositionRequest
            //instance = new ConvertPositionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConvertPositionRequest
        /// </summary>
        [Test]
        public void ConvertPositionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConvertPositionRequest
            //Assert.IsInstanceOfType<ConvertPositionRequest> (instance, "variable 'instance' is a ConvertPositionRequest");
        }


        /// <summary>
        /// Test the property 'InstrumentToken'
        /// </summary>
        [Test]
        public void InstrumentTokenTest()
        {
            // TODO unit test for the property 'InstrumentToken'
        }
        /// <summary>
        /// Test the property 'NewProduct'
        /// </summary>
        [Test]
        public void NewProductTest()
        {
            // TODO unit test for the property 'NewProduct'
        }
        /// <summary>
        /// Test the property 'OldProduct'
        /// </summary>
        [Test]
        public void OldProductTest()
        {
            // TODO unit test for the property 'OldProduct'
        }
        /// <summary>
        /// Test the property 'TransactionType'
        /// </summary>
        [Test]
        public void TransactionTypeTest()
        {
            // TODO unit test for the property 'TransactionType'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
