/* 
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UpstoxClient.Api;
using UpstoxClient.Model;
using UpstoxClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace UpstoxClient.Test
{
    /// <summary>
    ///  Class for testing ModifyOrderData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModifyOrderDataTests
    {
        // TODO uncomment below to declare an instance variable for ModifyOrderData
        //private ModifyOrderData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModifyOrderData
            //instance = new ModifyOrderData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModifyOrderData
        /// </summary>
        [Test]
        public void ModifyOrderDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModifyOrderData
            //Assert.IsInstanceOfType<ModifyOrderData> (instance, "variable 'instance' is a ModifyOrderData");
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }

    }

}
