/* 
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UpstoxClient.Api;
using UpstoxClient.Model;
using UpstoxClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace UpstoxClient.Test
{
    /// <summary>
    ///  Class for testing OAuthClientException
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OAuthClientExceptionTests
    {
        // TODO uncomment below to declare an instance variable for OAuthClientException
        //private OAuthClientException instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OAuthClientException
            //instance = new OAuthClientException();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OAuthClientException
        /// </summary>
        [Test]
        public void OAuthClientExceptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OAuthClientException
            //Assert.IsInstanceOfType<OAuthClientException> (instance, "variable 'instance' is a OAuthClientException");
        }


        /// <summary>
        /// Test the property 'Cause'
        /// </summary>
        [Test]
        public void CauseTest()
        {
            // TODO unit test for the property 'Cause'
        }
        /// <summary>
        /// Test the property 'StackTrace'
        /// </summary>
        [Test]
        public void StackTraceTest()
        {
            // TODO unit test for the property 'StackTrace'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Suppressed'
        /// </summary>
        [Test]
        public void SuppressedTest()
        {
            // TODO unit test for the property 'Suppressed'
        }
        /// <summary>
        /// Test the property 'LocalizedMessage'
        /// </summary>
        [Test]
        public void LocalizedMessageTest()
        {
            // TODO unit test for the property 'LocalizedMessage'
        }

    }

}
