/* 
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using UpstoxClient.Api;
using UpstoxClient.Model;
using UpstoxClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace UpstoxClient.Test
{
    /// <summary>
    ///  Class for testing TokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TokenRequestTests
    {
        // TODO uncomment below to declare an instance variable for TokenRequest
        //private TokenRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TokenRequest
            //instance = new TokenRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TokenRequest
        /// </summary>
        [Test]
        public void TokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TokenRequest
            //Assert.IsInstanceOfType<TokenRequest> (instance, "variable 'instance' is a TokenRequest");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Test]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }
        /// <summary>
        /// Test the property 'RedirectUri'
        /// </summary>
        [Test]
        public void RedirectUriTest()
        {
            // TODO unit test for the property 'RedirectUri'
        }
        /// <summary>
        /// Test the property 'GrantType'
        /// </summary>
        [Test]
        public void GrantTypeTest()
        {
            // TODO unit test for the property 'GrantType'
        }

    }

}
