// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// AnalyticsData
    /// </summary>
    public partial class AnalyticsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AnalyticsData" /> class.
        /// </summary>
        /// <param name="vega">vega</param>
        /// <param name="theta">theta</param>
        /// <param name="gamma">gamma</param>
        /// <param name="delta">delta</param>
        /// <param name="iv">iv</param>
        /// <param name="pop">pop</param>
        [JsonConstructor]
        public AnalyticsData(Option<double?> vega = default, Option<double?> theta = default, Option<double?> gamma = default, Option<double?> delta = default, Option<double?> iv = default, Option<double?> pop = default)
        {
            VegaOption = vega;
            ThetaOption = theta;
            GammaOption = gamma;
            DeltaOption = delta;
            IvOption = iv;
            PopOption = pop;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Vega
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> VegaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Vega
        /// </summary>
        [JsonPropertyName("vega")]
        public double? Vega { get { return this.VegaOption; } set { this.VegaOption = new(value); } }

        /// <summary>
        /// Used to track the state of Theta
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> ThetaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Theta
        /// </summary>
        [JsonPropertyName("theta")]
        public double? Theta { get { return this.ThetaOption; } set { this.ThetaOption = new(value); } }

        /// <summary>
        /// Used to track the state of Gamma
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> GammaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Gamma
        /// </summary>
        [JsonPropertyName("gamma")]
        public double? Gamma { get { return this.GammaOption; } set { this.GammaOption = new(value); } }

        /// <summary>
        /// Used to track the state of Delta
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> DeltaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Delta
        /// </summary>
        [JsonPropertyName("delta")]
        public double? Delta { get { return this.DeltaOption; } set { this.DeltaOption = new(value); } }

        /// <summary>
        /// Used to track the state of Iv
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> IvOption { get; private set; }

        /// <summary>
        /// Gets or Sets Iv
        /// </summary>
        [JsonPropertyName("iv")]
        public double? Iv { get { return this.IvOption; } set { this.IvOption = new(value); } }

        /// <summary>
        /// Used to track the state of Pop
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> PopOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pop
        /// </summary>
        [JsonPropertyName("pop")]
        public double? Pop { get { return this.PopOption; } set { this.PopOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AnalyticsData {\n");
            sb.Append("  Vega: ").Append(Vega).Append("\n");
            sb.Append("  Theta: ").Append(Theta).Append("\n");
            sb.Append("  Gamma: ").Append(Gamma).Append("\n");
            sb.Append("  Delta: ").Append(Delta).Append("\n");
            sb.Append("  Iv: ").Append(Iv).Append("\n");
            sb.Append("  Pop: ").Append(Pop).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AnalyticsData" />
    /// </summary>
    public class AnalyticsDataJsonConverter : JsonConverter<AnalyticsData>
    {
        /// <summary>
        /// Deserializes json to <see cref="AnalyticsData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AnalyticsData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> vega = default;
            Option<double?> theta = default;
            Option<double?> gamma = default;
            Option<double?> delta = default;
            Option<double?> iv = default;
            Option<double?> pop = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "vega":
                            vega = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "theta":
                            theta = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "gamma":
                            gamma = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "delta":
                            delta = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "iv":
                            iv = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "pop":
                            pop = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new AnalyticsData(vega, theta, gamma, delta, iv, pop);
        }

        /// <summary>
        /// Serializes a <see cref="AnalyticsData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="analyticsData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AnalyticsData analyticsData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, analyticsData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AnalyticsData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="analyticsData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AnalyticsData analyticsData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (analyticsData.VegaOption.IsSet)
                if (analyticsData.VegaOption.Value != null)
                    writer.WriteNumber("vega", analyticsData.VegaOption.Value!.Value);
                else
                    writer.WriteNull("vega");

            if (analyticsData.ThetaOption.IsSet)
                if (analyticsData.ThetaOption.Value != null)
                    writer.WriteNumber("theta", analyticsData.ThetaOption.Value!.Value);
                else
                    writer.WriteNull("theta");

            if (analyticsData.GammaOption.IsSet)
                if (analyticsData.GammaOption.Value != null)
                    writer.WriteNumber("gamma", analyticsData.GammaOption.Value!.Value);
                else
                    writer.WriteNull("gamma");

            if (analyticsData.DeltaOption.IsSet)
                if (analyticsData.DeltaOption.Value != null)
                    writer.WriteNumber("delta", analyticsData.DeltaOption.Value!.Value);
                else
                    writer.WriteNull("delta");

            if (analyticsData.IvOption.IsSet)
                if (analyticsData.IvOption.Value != null)
                    writer.WriteNumber("iv", analyticsData.IvOption.Value!.Value);
                else
                    writer.WriteNull("iv");

            if (analyticsData.PopOption.IsSet)
                if (analyticsData.PopOption.Value != null)
                    writer.WriteNumber("pop", analyticsData.PopOption.Value!.Value);
                else
                    writer.WriteNull("pop");
        }
    }
}
