// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// CancelOrExitMultiOrderResponse
    /// </summary>
    public partial class CancelOrExitMultiOrderResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CancelOrExitMultiOrderResponse" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="data">Response data for cancel or exit order request</param>
        /// <param name="errors">Error data for cancel or exit order request</param>
        /// <param name="summary">Execution summary for cancel or exit order request</param>
        [JsonConstructor]
        public CancelOrExitMultiOrderResponse(Option<StatusEnum?> status = default, Option<CancelOrExitMultiOrderData?> data = default, Option<List<CancelOrExitOrderErrorData>?> errors = default, Option<BatchExecutionSummary?> summary = default)
        {
            StatusOption = status;
            DataOption = data;
            ErrorsOption = errors;
            SummaryOption = summary;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Success for value: success
            /// </summary>
            Success = 1,

            /// <summary>
            /// Enum Error for value: error
            /// </summary>
            Error = 2,

            /// <summary>
            /// Enum PartialSuccess for value: partial_success
            /// </summary>
            PartialSuccess = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("success"))
                return StatusEnum.Success;

            if (value.Equals("error"))
                return StatusEnum.Error;

            if (value.Equals("partial_success"))
                return StatusEnum.PartialSuccess;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("success"))
                return StatusEnum.Success;

            if (value.Equals("error"))
                return StatusEnum.Error;

            if (value.Equals("partial_success"))
                return StatusEnum.PartialSuccess;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string? StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == null)
                return null;

            if (value == StatusEnum.Success)
                return "success";

            if (value == StatusEnum.Error)
                return "error";

            if (value == StatusEnum.PartialSuccess)
                return "partial_success";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CancelOrExitMultiOrderData?> DataOption { get; private set; }

        /// <summary>
        /// Response data for cancel or exit order request
        /// </summary>
        /// <value>Response data for cancel or exit order request</value>
        [JsonPropertyName("data")]
        public CancelOrExitMultiOrderData? Data { get { return this.DataOption; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Used to track the state of Errors
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CancelOrExitOrderErrorData>?> ErrorsOption { get; private set; }

        /// <summary>
        /// Error data for cancel or exit order request
        /// </summary>
        /// <value>Error data for cancel or exit order request</value>
        [JsonPropertyName("errors")]
        public List<CancelOrExitOrderErrorData>? Errors { get { return this.ErrorsOption; } set { this.ErrorsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Summary
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<BatchExecutionSummary?> SummaryOption { get; private set; }

        /// <summary>
        /// Execution summary for cancel or exit order request
        /// </summary>
        /// <value>Execution summary for cancel or exit order request</value>
        [JsonPropertyName("summary")]
        public BatchExecutionSummary? Summary { get { return this.SummaryOption; } set { this.SummaryOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CancelOrExitMultiOrderResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CancelOrExitMultiOrderResponse" />
    /// </summary>
    public class CancelOrExitMultiOrderResponseJsonConverter : JsonConverter<CancelOrExitMultiOrderResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="CancelOrExitMultiOrderResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CancelOrExitMultiOrderResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<CancelOrExitMultiOrderResponse.StatusEnum?> status = default;
            Option<CancelOrExitMultiOrderData?> data = default;
            Option<List<CancelOrExitOrderErrorData>?> errors = default;
            Option<BatchExecutionSummary?> summary = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<CancelOrExitMultiOrderResponse.StatusEnum?>(CancelOrExitMultiOrderResponse.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "data":
                            data = new Option<CancelOrExitMultiOrderData?>(JsonSerializer.Deserialize<CancelOrExitMultiOrderData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "errors":
                            errors = new Option<List<CancelOrExitOrderErrorData>?>(JsonSerializer.Deserialize<List<CancelOrExitOrderErrorData>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "summary":
                            summary = new Option<BatchExecutionSummary?>(JsonSerializer.Deserialize<BatchExecutionSummary>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class CancelOrExitMultiOrderResponse.");

            return new CancelOrExitMultiOrderResponse(status, data, errors, summary);
        }

        /// <summary>
        /// Serializes a <see cref="CancelOrExitMultiOrderResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cancelOrExitMultiOrderResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CancelOrExitMultiOrderResponse cancelOrExitMultiOrderResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, cancelOrExitMultiOrderResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CancelOrExitMultiOrderResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="cancelOrExitMultiOrderResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CancelOrExitMultiOrderResponse cancelOrExitMultiOrderResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (cancelOrExitMultiOrderResponse.DataOption.IsSet && cancelOrExitMultiOrderResponse.Data == null)
                throw new ArgumentNullException(nameof(cancelOrExitMultiOrderResponse.Data), "Property is required for class CancelOrExitMultiOrderResponse.");

            if (cancelOrExitMultiOrderResponse.ErrorsOption.IsSet && cancelOrExitMultiOrderResponse.Errors == null)
                throw new ArgumentNullException(nameof(cancelOrExitMultiOrderResponse.Errors), "Property is required for class CancelOrExitMultiOrderResponse.");

            if (cancelOrExitMultiOrderResponse.SummaryOption.IsSet && cancelOrExitMultiOrderResponse.Summary == null)
                throw new ArgumentNullException(nameof(cancelOrExitMultiOrderResponse.Summary), "Property is required for class CancelOrExitMultiOrderResponse.");

            var statusRawValue = CancelOrExitMultiOrderResponse.StatusEnumToJsonValue(cancelOrExitMultiOrderResponse.StatusOption.Value!.Value);
            if (statusRawValue != null)
                writer.WriteString("status", statusRawValue);
            else
                writer.WriteNull("status");

            if (cancelOrExitMultiOrderResponse.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, cancelOrExitMultiOrderResponse.Data, jsonSerializerOptions);
            }
            if (cancelOrExitMultiOrderResponse.ErrorsOption.IsSet)
            {
                writer.WritePropertyName("errors");
                JsonSerializer.Serialize(writer, cancelOrExitMultiOrderResponse.Errors, jsonSerializerOptions);
            }
            if (cancelOrExitMultiOrderResponse.SummaryOption.IsSet)
            {
                writer.WritePropertyName("summary");
                JsonSerializer.Serialize(writer, cancelOrExitMultiOrderResponse.Summary, jsonSerializerOptions);
            }
        }
    }
}
