// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// FinancialStatementEntry
    /// </summary>
    public partial class FinancialStatementEntry
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FinancialStatementEntry" /> class.
        /// </summary>
        /// <param name="particular">Type of financial statement line item</param>
        /// <param name="history">Historical values for this statement line item</param>
        [JsonConstructor]
        internal FinancialStatementEntry(Option<string?> particular = default, Option<List<HistoryItem>?> history = default)
        {
            ParticularOption = particular;
            HistoryOption = history;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Particular
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ParticularOption { get; }

        /// <summary>
        /// Type of financial statement line item
        /// </summary>
        /// <value>Type of financial statement line item</value>
        /* <example>Revenue</example> */
        [JsonPropertyName("particular")]
        public string? Particular { get { return this.ParticularOption.Value; } }

        /// <summary>
        /// Used to track the state of History
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<HistoryItem>?> HistoryOption { get; }

        /// <summary>
        /// Historical values for this statement line item
        /// </summary>
        /// <value>Historical values for this statement line item</value>
        [JsonPropertyName("history")]
        public List<HistoryItem>? History { get { return this.HistoryOption.Value; } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FinancialStatementEntry {\n");
            sb.Append("  Particular: ").Append(Particular).Append("\n");
            sb.Append("  History: ").Append(History).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FinancialStatementEntry" />
    /// </summary>
    public class FinancialStatementEntryJsonConverter : JsonConverter<FinancialStatementEntry>
    {
        /// <summary>
        /// Deserializes json to <see cref="FinancialStatementEntry" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FinancialStatementEntry Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> particular = default;
            Option<List<HistoryItem>?> history = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "particular":
                            particular = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "history":
                            history = new Option<List<HistoryItem>?>(JsonSerializer.Deserialize<List<HistoryItem>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (history.IsSet && history.Value == null)
                throw new ArgumentNullException(nameof(history), "Property is not nullable for class FinancialStatementEntry.");

            return new FinancialStatementEntry(particular, history);
        }

        /// <summary>
        /// Serializes a <see cref="FinancialStatementEntry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="financialStatementEntry"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FinancialStatementEntry financialStatementEntry, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, financialStatementEntry, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FinancialStatementEntry" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="financialStatementEntry"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FinancialStatementEntry financialStatementEntry, JsonSerializerOptions jsonSerializerOptions)
        {
            if (financialStatementEntry.HistoryOption.IsSet && financialStatementEntry.History == null)
                throw new ArgumentNullException(nameof(financialStatementEntry.History), "Property is required for class FinancialStatementEntry.");

            if (financialStatementEntry.ParticularOption.IsSet)
                if (financialStatementEntry.ParticularOption.Value != null)
                    writer.WriteString("particular", financialStatementEntry.Particular);
                else
                    writer.WriteNull("particular");

            if (financialStatementEntry.HistoryOption.IsSet)
            {
                writer.WritePropertyName("history");
                JsonSerializer.Serialize(writer, financialStatementEntry.History, jsonSerializerOptions);
            }
        }
    }
}
