// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// GetMarketQuoteOHLCResponse
    /// </summary>
    public partial class GetMarketQuoteOHLCResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetMarketQuoteOHLCResponse" /> class.
        /// </summary>
        /// <param name="status">status</param>
        /// <param name="data">data</param>
        [JsonConstructor]
        public GetMarketQuoteOHLCResponse(Option<StatusEnum?> status = default, Option<Dictionary<string, MarketQuoteOHLC>?> data = default)
        {
            StatusOption = status;
            DataOption = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Success for value: success
            /// </summary>
            Success = 1,

            /// <summary>
            /// Enum Error for value: error
            /// </summary>
            Error = 2,

            /// <summary>
            /// Enum PartialSuccess for value: partial_success
            /// </summary>
            PartialSuccess = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("success"))
                return StatusEnum.Success;

            if (value.Equals("error"))
                return StatusEnum.Error;

            if (value.Equals("partial_success"))
                return StatusEnum.PartialSuccess;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("success"))
                return StatusEnum.Success;

            if (value.Equals("error"))
                return StatusEnum.Error;

            if (value.Equals("partial_success"))
                return StatusEnum.PartialSuccess;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string? StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == null)
                return null;

            if (value == StatusEnum.Success)
                return "success";

            if (value == StatusEnum.Error)
                return "error";

            if (value == StatusEnum.PartialSuccess)
                return "partial_success";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, MarketQuoteOHLC>?> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public Dictionary<string, MarketQuoteOHLC>? Data { get { return this.DataOption; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetMarketQuoteOHLCResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetMarketQuoteOHLCResponse" />
    /// </summary>
    public class GetMarketQuoteOHLCResponseJsonConverter : JsonConverter<GetMarketQuoteOHLCResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetMarketQuoteOHLCResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetMarketQuoteOHLCResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<GetMarketQuoteOHLCResponse.StatusEnum?> status = default;
            Option<Dictionary<string, MarketQuoteOHLC>?> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<GetMarketQuoteOHLCResponse.StatusEnum?>(GetMarketQuoteOHLCResponse.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "data":
                            data = new Option<Dictionary<string, MarketQuoteOHLC>?>(JsonSerializer.Deserialize<Dictionary<string, MarketQuoteOHLC>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class GetMarketQuoteOHLCResponse.");

            return new GetMarketQuoteOHLCResponse(status, data);
        }

        /// <summary>
        /// Serializes a <see cref="GetMarketQuoteOHLCResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMarketQuoteOHLCResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetMarketQuoteOHLCResponse getMarketQuoteOHLCResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getMarketQuoteOHLCResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetMarketQuoteOHLCResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getMarketQuoteOHLCResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetMarketQuoteOHLCResponse getMarketQuoteOHLCResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getMarketQuoteOHLCResponse.DataOption.IsSet && getMarketQuoteOHLCResponse.Data == null)
                throw new ArgumentNullException(nameof(getMarketQuoteOHLCResponse.Data), "Property is required for class GetMarketQuoteOHLCResponse.");

            var statusRawValue = GetMarketQuoteOHLCResponse.StatusEnumToJsonValue(getMarketQuoteOHLCResponse.StatusOption.Value!.Value);
            if (statusRawValue != null)
                writer.WriteString("status", statusRawValue);
            else
                writer.WriteNull("status");

            if (getMarketQuoteOHLCResponse.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, getMarketQuoteOHLCResponse.Data, jsonSerializerOptions);
            }
        }
    }
}
