// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// KeyRatioData
    /// </summary>
    public partial class KeyRatioData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyRatioData" /> class.
        /// </summary>
        /// <param name="name">Name of the ratio</param>
        /// <param name="companyValue">Ratio value for the company</param>
        /// <param name="sectorValue">Ratio value for the sector reference</param>
        [JsonConstructor]
        internal KeyRatioData(Option<string?> name = default, Option<string?> companyValue = default, Option<string?> sectorValue = default)
        {
            NameOption = name;
            CompanyValueOption = companyValue;
            SectorValueOption = sectorValue;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; }

        /// <summary>
        /// Name of the ratio
        /// </summary>
        /// <value>Name of the ratio</value>
        /* <example>P/E</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } }

        /// <summary>
        /// Used to track the state of CompanyValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CompanyValueOption { get; }

        /// <summary>
        /// Ratio value for the company
        /// </summary>
        /// <value>Ratio value for the company</value>
        /* <example>20.15</example> */
        [JsonPropertyName("company_value")]
        public string? CompanyValue { get { return this.CompanyValueOption.Value; } }

        /// <summary>
        /// Used to track the state of SectorValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SectorValueOption { get; }

        /// <summary>
        /// Ratio value for the sector reference
        /// </summary>
        /// <value>Ratio value for the sector reference</value>
        /* <example>12.46</example> */
        [JsonPropertyName("sector_value")]
        public string? SectorValue { get { return this.SectorValueOption.Value; } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KeyRatioData {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CompanyValue: ").Append(CompanyValue).Append("\n");
            sb.Append("  SectorValue: ").Append(SectorValue).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="KeyRatioData" />
    /// </summary>
    public class KeyRatioDataJsonConverter : JsonConverter<KeyRatioData>
    {
        /// <summary>
        /// Deserializes json to <see cref="KeyRatioData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override KeyRatioData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> companyValue = default;
            Option<string?> sectorValue = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "company_value":
                            companyValue = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "sector_value":
                            sectorValue = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new KeyRatioData(name, companyValue, sectorValue);
        }

        /// <summary>
        /// Serializes a <see cref="KeyRatioData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="keyRatioData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, KeyRatioData keyRatioData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, keyRatioData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="KeyRatioData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="keyRatioData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, KeyRatioData keyRatioData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (keyRatioData.NameOption.IsSet)
                if (keyRatioData.NameOption.Value != null)
                    writer.WriteString("name", keyRatioData.Name);
                else
                    writer.WriteNull("name");

            if (keyRatioData.CompanyValueOption.IsSet)
                if (keyRatioData.CompanyValueOption.Value != null)
                    writer.WriteString("company_value", keyRatioData.CompanyValue);
                else
                    writer.WriteNull("company_value");

            if (keyRatioData.SectorValueOption.IsSet)
                if (keyRatioData.SectorValueOption.Value != null)
                    writer.WriteString("sector_value", keyRatioData.SectorValue);
                else
                    writer.WriteNull("sector_value");
        }
    }
}
