// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// MarketQuoteOptionGreekV3
    /// </summary>
    public partial class MarketQuoteOptionGreekV3
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketQuoteOptionGreekV3" /> class.
        /// </summary>
        /// <param name="lastPrice">lastPrice</param>
        /// <param name="instrumentToken">instrumentToken</param>
        /// <param name="ltq">ltq</param>
        /// <param name="volume">volume</param>
        /// <param name="cp">cp</param>
        /// <param name="iv">iv</param>
        /// <param name="vega">vega</param>
        /// <param name="gamma">gamma</param>
        /// <param name="theta">theta</param>
        /// <param name="delta">delta</param>
        /// <param name="oi">oi</param>
        [JsonConstructor]
        public MarketQuoteOptionGreekV3(Option<double?> lastPrice = default, Option<string?> instrumentToken = default, Option<long?> ltq = default, Option<long?> volume = default, Option<double?> cp = default, Option<double?> iv = default, Option<double?> vega = default, Option<double?> gamma = default, Option<double?> theta = default, Option<double?> delta = default, Option<double?> oi = default)
        {
            LastPriceOption = lastPrice;
            InstrumentTokenOption = instrumentToken;
            LtqOption = ltq;
            VolumeOption = volume;
            CpOption = cp;
            IvOption = iv;
            VegaOption = vega;
            GammaOption = gamma;
            ThetaOption = theta;
            DeltaOption = delta;
            OiOption = oi;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of LastPrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> LastPriceOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastPrice
        /// </summary>
        [JsonPropertyName("last_price")]
        public double? LastPrice { get { return this.LastPriceOption; } set { this.LastPriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of InstrumentToken
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstrumentTokenOption { get; private set; }

        /// <summary>
        /// Gets or Sets InstrumentToken
        /// </summary>
        [JsonPropertyName("instrument_token")]
        public string? InstrumentToken { get { return this.InstrumentTokenOption; } set { this.InstrumentTokenOption = new(value); } }

        /// <summary>
        /// Used to track the state of Ltq
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> LtqOption { get; private set; }

        /// <summary>
        /// Gets or Sets Ltq
        /// </summary>
        [JsonPropertyName("ltq")]
        public long? Ltq { get { return this.LtqOption; } set { this.LtqOption = new(value); } }

        /// <summary>
        /// Used to track the state of Volume
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> VolumeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Volume
        /// </summary>
        [JsonPropertyName("volume")]
        public long? Volume { get { return this.VolumeOption; } set { this.VolumeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> CpOption { get; private set; }

        /// <summary>
        /// Gets or Sets Cp
        /// </summary>
        [JsonPropertyName("cp")]
        public double? Cp { get { return this.CpOption; } set { this.CpOption = new(value); } }

        /// <summary>
        /// Used to track the state of Iv
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> IvOption { get; private set; }

        /// <summary>
        /// Gets or Sets Iv
        /// </summary>
        [JsonPropertyName("iv")]
        public double? Iv { get { return this.IvOption; } set { this.IvOption = new(value); } }

        /// <summary>
        /// Used to track the state of Vega
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> VegaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Vega
        /// </summary>
        [JsonPropertyName("vega")]
        public double? Vega { get { return this.VegaOption; } set { this.VegaOption = new(value); } }

        /// <summary>
        /// Used to track the state of Gamma
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> GammaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Gamma
        /// </summary>
        [JsonPropertyName("gamma")]
        public double? Gamma { get { return this.GammaOption; } set { this.GammaOption = new(value); } }

        /// <summary>
        /// Used to track the state of Theta
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> ThetaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Theta
        /// </summary>
        [JsonPropertyName("theta")]
        public double? Theta { get { return this.ThetaOption; } set { this.ThetaOption = new(value); } }

        /// <summary>
        /// Used to track the state of Delta
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> DeltaOption { get; private set; }

        /// <summary>
        /// Gets or Sets Delta
        /// </summary>
        [JsonPropertyName("delta")]
        public double? Delta { get { return this.DeltaOption; } set { this.DeltaOption = new(value); } }

        /// <summary>
        /// Used to track the state of Oi
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> OiOption { get; private set; }

        /// <summary>
        /// Gets or Sets Oi
        /// </summary>
        [JsonPropertyName("oi")]
        public double? Oi { get { return this.OiOption; } set { this.OiOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MarketQuoteOptionGreekV3 {\n");
            sb.Append("  LastPrice: ").Append(LastPrice).Append("\n");
            sb.Append("  InstrumentToken: ").Append(InstrumentToken).Append("\n");
            sb.Append("  Ltq: ").Append(Ltq).Append("\n");
            sb.Append("  Volume: ").Append(Volume).Append("\n");
            sb.Append("  Cp: ").Append(Cp).Append("\n");
            sb.Append("  Iv: ").Append(Iv).Append("\n");
            sb.Append("  Vega: ").Append(Vega).Append("\n");
            sb.Append("  Gamma: ").Append(Gamma).Append("\n");
            sb.Append("  Theta: ").Append(Theta).Append("\n");
            sb.Append("  Delta: ").Append(Delta).Append("\n");
            sb.Append("  Oi: ").Append(Oi).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MarketQuoteOptionGreekV3" />
    /// </summary>
    public class MarketQuoteOptionGreekV3JsonConverter : JsonConverter<MarketQuoteOptionGreekV3>
    {
        /// <summary>
        /// Deserializes json to <see cref="MarketQuoteOptionGreekV3" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MarketQuoteOptionGreekV3 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<double?> lastPrice = default;
            Option<string?> instrumentToken = default;
            Option<long?> ltq = default;
            Option<long?> volume = default;
            Option<double?> cp = default;
            Option<double?> iv = default;
            Option<double?> vega = default;
            Option<double?> gamma = default;
            Option<double?> theta = default;
            Option<double?> delta = default;
            Option<double?> oi = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "last_price":
                            lastPrice = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "instrument_token":
                            instrumentToken = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "ltq":
                            ltq = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "volume":
                            volume = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "cp":
                            cp = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "iv":
                            iv = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "vega":
                            vega = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "gamma":
                            gamma = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "theta":
                            theta = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "delta":
                            delta = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "oi":
                            oi = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new MarketQuoteOptionGreekV3(lastPrice, instrumentToken, ltq, volume, cp, iv, vega, gamma, theta, delta, oi);
        }

        /// <summary>
        /// Serializes a <see cref="MarketQuoteOptionGreekV3" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="marketQuoteOptionGreekV3"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MarketQuoteOptionGreekV3 marketQuoteOptionGreekV3, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, marketQuoteOptionGreekV3, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MarketQuoteOptionGreekV3" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="marketQuoteOptionGreekV3"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MarketQuoteOptionGreekV3 marketQuoteOptionGreekV3, JsonSerializerOptions jsonSerializerOptions)
        {
            if (marketQuoteOptionGreekV3.LastPriceOption.IsSet)
                if (marketQuoteOptionGreekV3.LastPriceOption.Value != null)
                    writer.WriteNumber("last_price", marketQuoteOptionGreekV3.LastPriceOption.Value!.Value);
                else
                    writer.WriteNull("last_price");

            if (marketQuoteOptionGreekV3.InstrumentTokenOption.IsSet)
                if (marketQuoteOptionGreekV3.InstrumentTokenOption.Value != null)
                    writer.WriteString("instrument_token", marketQuoteOptionGreekV3.InstrumentToken);
                else
                    writer.WriteNull("instrument_token");

            if (marketQuoteOptionGreekV3.LtqOption.IsSet)
                if (marketQuoteOptionGreekV3.LtqOption.Value != null)
                    writer.WriteNumber("ltq", marketQuoteOptionGreekV3.LtqOption.Value!.Value);
                else
                    writer.WriteNull("ltq");

            if (marketQuoteOptionGreekV3.VolumeOption.IsSet)
                if (marketQuoteOptionGreekV3.VolumeOption.Value != null)
                    writer.WriteNumber("volume", marketQuoteOptionGreekV3.VolumeOption.Value!.Value);
                else
                    writer.WriteNull("volume");

            if (marketQuoteOptionGreekV3.CpOption.IsSet)
                if (marketQuoteOptionGreekV3.CpOption.Value != null)
                    writer.WriteNumber("cp", marketQuoteOptionGreekV3.CpOption.Value!.Value);
                else
                    writer.WriteNull("cp");

            if (marketQuoteOptionGreekV3.IvOption.IsSet)
                if (marketQuoteOptionGreekV3.IvOption.Value != null)
                    writer.WriteNumber("iv", marketQuoteOptionGreekV3.IvOption.Value!.Value);
                else
                    writer.WriteNull("iv");

            if (marketQuoteOptionGreekV3.VegaOption.IsSet)
                if (marketQuoteOptionGreekV3.VegaOption.Value != null)
                    writer.WriteNumber("vega", marketQuoteOptionGreekV3.VegaOption.Value!.Value);
                else
                    writer.WriteNull("vega");

            if (marketQuoteOptionGreekV3.GammaOption.IsSet)
                if (marketQuoteOptionGreekV3.GammaOption.Value != null)
                    writer.WriteNumber("gamma", marketQuoteOptionGreekV3.GammaOption.Value!.Value);
                else
                    writer.WriteNull("gamma");

            if (marketQuoteOptionGreekV3.ThetaOption.IsSet)
                if (marketQuoteOptionGreekV3.ThetaOption.Value != null)
                    writer.WriteNumber("theta", marketQuoteOptionGreekV3.ThetaOption.Value!.Value);
                else
                    writer.WriteNull("theta");

            if (marketQuoteOptionGreekV3.DeltaOption.IsSet)
                if (marketQuoteOptionGreekV3.DeltaOption.Value != null)
                    writer.WriteNumber("delta", marketQuoteOptionGreekV3.DeltaOption.Value!.Value);
                else
                    writer.WriteNull("delta");

            if (marketQuoteOptionGreekV3.OiOption.IsSet)
                if (marketQuoteOptionGreekV3.OiOption.Value != null)
                    writer.WriteNumber("oi", marketQuoteOptionGreekV3.OiOption.Value!.Value);
                else
                    writer.WriteNull("oi");
        }
    }
}
