// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// MutualFundOrderData
    /// </summary>
    public partial class MutualFundOrderData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MutualFundOrderData" /> class.
        /// </summary>
        /// <param name="status">Current status of the order.</param>
        /// <param name="folio">Folio number, when allotted.</param>
        /// <param name="fund">Display name of the fund.</param>
        /// <param name="amount">Order amount.</param>
        /// <param name="variety">Order variety or channel-specific classification, if available.</param>
        /// <param name="quantity">Units allotted or sold.</param>
        /// <param name="price">Price or NAV used for the transaction, when available.</param>
        /// <param name="orderId">Unique order identifier.</param>
        /// <param name="exchangeOrderId">Exchange-generated order id, if available.</param>
        /// <param name="instrumentKey">ISIN of the fund, when available.</param>
        /// <param name="statusMessage">Human-readable status or rejection reason.</param>
        /// <param name="orderTimestamp">Timestamp when the order was registered.</param>
        /// <param name="exchangeTimestamp">Exchange date for the order, if available.</param>
        /// <param name="settlementId">Exchange settlement id, if available.</param>
        /// <param name="transactionType">BUY or SELL.</param>
        /// <param name="purchaseType">FRESH or ADDITIONAL for buys, when available.</param>
        /// <param name="lastPrice">Last known NAV.</param>
        /// <param name="averagePrice">Allotted or sold NAV.</param>
        /// <param name="lastPriceDate">Date for which last NAV is available.</param>
        [JsonConstructor]
        public MutualFundOrderData(Option<string?> status = default, Option<string?> folio = default, Option<string?> fund = default, Option<double?> amount = default, Option<string?> variety = default, Option<double?> quantity = default, Option<double?> price = default, Option<string?> orderId = default, Option<string?> exchangeOrderId = default, Option<string?> instrumentKey = default, Option<string?> statusMessage = default, Option<string?> orderTimestamp = default, Option<string?> exchangeTimestamp = default, Option<string?> settlementId = default, Option<string?> transactionType = default, Option<string?> purchaseType = default, Option<double?> lastPrice = default, Option<double?> averagePrice = default, Option<string?> lastPriceDate = default)
        {
            StatusOption = status;
            FolioOption = folio;
            FundOption = fund;
            AmountOption = amount;
            VarietyOption = variety;
            QuantityOption = quantity;
            PriceOption = price;
            OrderIdOption = orderId;
            ExchangeOrderIdOption = exchangeOrderId;
            InstrumentKeyOption = instrumentKey;
            StatusMessageOption = statusMessage;
            OrderTimestampOption = orderTimestamp;
            ExchangeTimestampOption = exchangeTimestamp;
            SettlementIdOption = settlementId;
            TransactionTypeOption = transactionType;
            PurchaseTypeOption = purchaseType;
            LastPriceOption = lastPrice;
            AveragePriceOption = averagePrice;
            LastPriceDateOption = lastPriceDate;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Current status of the order.
        /// </summary>
        /// <value>Current status of the order.</value>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Folio
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FolioOption { get; private set; }

        /// <summary>
        /// Folio number, when allotted.
        /// </summary>
        /// <value>Folio number, when allotted.</value>
        [JsonPropertyName("folio")]
        public string? Folio { get { return this.FolioOption.Value; } set { this.FolioOption = new(value); } }

        /// <summary>
        /// Used to track the state of Fund
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FundOption { get; private set; }

        /// <summary>
        /// Display name of the fund.
        /// </summary>
        /// <value>Display name of the fund.</value>
        [JsonPropertyName("fund")]
        public string? Fund { get { return this.FundOption.Value; } set { this.FundOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AmountOption { get; private set; }

        /// <summary>
        /// Order amount.
        /// </summary>
        /// <value>Order amount.</value>
        [JsonPropertyName("amount")]
        public double? Amount { get { return this.AmountOption.Value; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Variety
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> VarietyOption { get; private set; }

        /// <summary>
        /// Order variety or channel-specific classification, if available.
        /// </summary>
        /// <value>Order variety or channel-specific classification, if available.</value>
        [JsonPropertyName("variety")]
        public string? Variety { get { return this.VarietyOption.Value; } set { this.VarietyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Quantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> QuantityOption { get; private set; }

        /// <summary>
        /// Units allotted or sold.
        /// </summary>
        /// <value>Units allotted or sold.</value>
        [JsonPropertyName("quantity")]
        public double? Quantity { get { return this.QuantityOption.Value; } set { this.QuantityOption = new(value); } }

        /// <summary>
        /// Used to track the state of Price
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> PriceOption { get; private set; }

        /// <summary>
        /// Price or NAV used for the transaction, when available.
        /// </summary>
        /// <value>Price or NAV used for the transaction, when available.</value>
        [JsonPropertyName("price")]
        public double? Price { get { return this.PriceOption.Value; } set { this.PriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of OrderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OrderIdOption { get; private set; }

        /// <summary>
        /// Unique order identifier.
        /// </summary>
        /// <value>Unique order identifier.</value>
        [JsonPropertyName("order_id")]
        public string? OrderId { get { return this.OrderIdOption.Value; } set { this.OrderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExchangeOrderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExchangeOrderIdOption { get; private set; }

        /// <summary>
        /// Exchange-generated order id, if available.
        /// </summary>
        /// <value>Exchange-generated order id, if available.</value>
        [JsonPropertyName("exchange_order_id")]
        public string? ExchangeOrderId { get { return this.ExchangeOrderIdOption.Value; } set { this.ExchangeOrderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InstrumentKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstrumentKeyOption { get; private set; }

        /// <summary>
        /// ISIN of the fund, when available.
        /// </summary>
        /// <value>ISIN of the fund, when available.</value>
        [JsonPropertyName("instrument_key")]
        public string? InstrumentKey { get { return this.InstrumentKeyOption.Value; } set { this.InstrumentKeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of StatusMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusMessageOption { get; private set; }

        /// <summary>
        /// Human-readable status or rejection reason.
        /// </summary>
        /// <value>Human-readable status or rejection reason.</value>
        [JsonPropertyName("status_message")]
        public string? StatusMessage { get { return this.StatusMessageOption.Value; } set { this.StatusMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of OrderTimestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OrderTimestampOption { get; private set; }

        /// <summary>
        /// Timestamp when the order was registered.
        /// </summary>
        /// <value>Timestamp when the order was registered.</value>
        [JsonPropertyName("order_timestamp")]
        public string? OrderTimestamp { get { return this.OrderTimestampOption.Value; } set { this.OrderTimestampOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExchangeTimestamp
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ExchangeTimestampOption { get; private set; }

        /// <summary>
        /// Exchange date for the order, if available.
        /// </summary>
        /// <value>Exchange date for the order, if available.</value>
        [JsonPropertyName("exchange_timestamp")]
        public string? ExchangeTimestamp { get { return this.ExchangeTimestampOption.Value; } set { this.ExchangeTimestampOption = new(value); } }

        /// <summary>
        /// Used to track the state of SettlementId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SettlementIdOption { get; private set; }

        /// <summary>
        /// Exchange settlement id, if available.
        /// </summary>
        /// <value>Exchange settlement id, if available.</value>
        [JsonPropertyName("settlement_id")]
        public string? SettlementId { get { return this.SettlementIdOption.Value; } set { this.SettlementIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TransactionTypeOption { get; private set; }

        /// <summary>
        /// BUY or SELL.
        /// </summary>
        /// <value>BUY or SELL.</value>
        [JsonPropertyName("transaction_type")]
        public string? TransactionType { get { return this.TransactionTypeOption.Value; } set { this.TransactionTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of PurchaseType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PurchaseTypeOption { get; private set; }

        /// <summary>
        /// FRESH or ADDITIONAL for buys, when available.
        /// </summary>
        /// <value>FRESH or ADDITIONAL for buys, when available.</value>
        [JsonPropertyName("purchase_type")]
        public string? PurchaseType { get { return this.PurchaseTypeOption.Value; } set { this.PurchaseTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastPrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> LastPriceOption { get; private set; }

        /// <summary>
        /// Last known NAV.
        /// </summary>
        /// <value>Last known NAV.</value>
        [JsonPropertyName("last_price")]
        public double? LastPrice { get { return this.LastPriceOption.Value; } set { this.LastPriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of AveragePrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AveragePriceOption { get; private set; }

        /// <summary>
        /// Allotted or sold NAV.
        /// </summary>
        /// <value>Allotted or sold NAV.</value>
        [JsonPropertyName("average_price")]
        public double? AveragePrice { get { return this.AveragePriceOption.Value; } set { this.AveragePriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastPriceDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LastPriceDateOption { get; private set; }

        /// <summary>
        /// Date for which last NAV is available.
        /// </summary>
        /// <value>Date for which last NAV is available.</value>
        [JsonPropertyName("last_price_date")]
        public string? LastPriceDate { get { return this.LastPriceDateOption.Value; } set { this.LastPriceDateOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MutualFundOrderData {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Folio: ").Append(Folio).Append("\n");
            sb.Append("  Fund: ").Append(Fund).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Variety: ").Append(Variety).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  ExchangeOrderId: ").Append(ExchangeOrderId).Append("\n");
            sb.Append("  InstrumentKey: ").Append(InstrumentKey).Append("\n");
            sb.Append("  StatusMessage: ").Append(StatusMessage).Append("\n");
            sb.Append("  OrderTimestamp: ").Append(OrderTimestamp).Append("\n");
            sb.Append("  ExchangeTimestamp: ").Append(ExchangeTimestamp).Append("\n");
            sb.Append("  SettlementId: ").Append(SettlementId).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("  PurchaseType: ").Append(PurchaseType).Append("\n");
            sb.Append("  LastPrice: ").Append(LastPrice).Append("\n");
            sb.Append("  AveragePrice: ").Append(AveragePrice).Append("\n");
            sb.Append("  LastPriceDate: ").Append(LastPriceDate).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MutualFundOrderData" />
    /// </summary>
    public class MutualFundOrderDataJsonConverter : JsonConverter<MutualFundOrderData>
    {
        /// <summary>
        /// Deserializes json to <see cref="MutualFundOrderData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MutualFundOrderData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> status = default;
            Option<string?> folio = default;
            Option<string?> fund = default;
            Option<double?> amount = default;
            Option<string?> variety = default;
            Option<double?> quantity = default;
            Option<double?> price = default;
            Option<string?> orderId = default;
            Option<string?> exchangeOrderId = default;
            Option<string?> instrumentKey = default;
            Option<string?> statusMessage = default;
            Option<string?> orderTimestamp = default;
            Option<string?> exchangeTimestamp = default;
            Option<string?> settlementId = default;
            Option<string?> transactionType = default;
            Option<string?> purchaseType = default;
            Option<double?> lastPrice = default;
            Option<double?> averagePrice = default;
            Option<string?> lastPriceDate = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "folio":
                            folio = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "fund":
                            fund = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "amount":
                            amount = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "variety":
                            variety = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "quantity":
                            quantity = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "price":
                            price = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "order_id":
                            orderId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "exchange_order_id":
                            exchangeOrderId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "instrument_key":
                            instrumentKey = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "status_message":
                            statusMessage = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "order_timestamp":
                            orderTimestamp = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "exchange_timestamp":
                            exchangeTimestamp = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "settlement_id":
                            settlementId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "transaction_type":
                            transactionType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "purchase_type":
                            purchaseType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "last_price":
                            lastPrice = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "average_price":
                            averagePrice = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "last_price_date":
                            lastPriceDate = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new MutualFundOrderData(status, folio, fund, amount, variety, quantity, price, orderId, exchangeOrderId, instrumentKey, statusMessage, orderTimestamp, exchangeTimestamp, settlementId, transactionType, purchaseType, lastPrice, averagePrice, lastPriceDate);
        }

        /// <summary>
        /// Serializes a <see cref="MutualFundOrderData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mutualFundOrderData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MutualFundOrderData mutualFundOrderData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mutualFundOrderData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MutualFundOrderData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mutualFundOrderData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MutualFundOrderData mutualFundOrderData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mutualFundOrderData.StatusOption.IsSet)
                if (mutualFundOrderData.StatusOption.Value != null)
                    writer.WriteString("status", mutualFundOrderData.Status);
                else
                    writer.WriteNull("status");

            if (mutualFundOrderData.FolioOption.IsSet)
                if (mutualFundOrderData.FolioOption.Value != null)
                    writer.WriteString("folio", mutualFundOrderData.Folio);
                else
                    writer.WriteNull("folio");

            if (mutualFundOrderData.FundOption.IsSet)
                if (mutualFundOrderData.FundOption.Value != null)
                    writer.WriteString("fund", mutualFundOrderData.Fund);
                else
                    writer.WriteNull("fund");

            if (mutualFundOrderData.AmountOption.IsSet)
                if (mutualFundOrderData.AmountOption.Value != null)
                    writer.WriteNumber("amount", mutualFundOrderData.AmountOption.Value!.Value);
                else
                    writer.WriteNull("amount");

            if (mutualFundOrderData.VarietyOption.IsSet)
                if (mutualFundOrderData.VarietyOption.Value != null)
                    writer.WriteString("variety", mutualFundOrderData.Variety);
                else
                    writer.WriteNull("variety");

            if (mutualFundOrderData.QuantityOption.IsSet)
                if (mutualFundOrderData.QuantityOption.Value != null)
                    writer.WriteNumber("quantity", mutualFundOrderData.QuantityOption.Value!.Value);
                else
                    writer.WriteNull("quantity");

            if (mutualFundOrderData.PriceOption.IsSet)
                if (mutualFundOrderData.PriceOption.Value != null)
                    writer.WriteNumber("price", mutualFundOrderData.PriceOption.Value!.Value);
                else
                    writer.WriteNull("price");

            if (mutualFundOrderData.OrderIdOption.IsSet)
                if (mutualFundOrderData.OrderIdOption.Value != null)
                    writer.WriteString("order_id", mutualFundOrderData.OrderId);
                else
                    writer.WriteNull("order_id");

            if (mutualFundOrderData.ExchangeOrderIdOption.IsSet)
                if (mutualFundOrderData.ExchangeOrderIdOption.Value != null)
                    writer.WriteString("exchange_order_id", mutualFundOrderData.ExchangeOrderId);
                else
                    writer.WriteNull("exchange_order_id");

            if (mutualFundOrderData.InstrumentKeyOption.IsSet)
                if (mutualFundOrderData.InstrumentKeyOption.Value != null)
                    writer.WriteString("instrument_key", mutualFundOrderData.InstrumentKey);
                else
                    writer.WriteNull("instrument_key");

            if (mutualFundOrderData.StatusMessageOption.IsSet)
                if (mutualFundOrderData.StatusMessageOption.Value != null)
                    writer.WriteString("status_message", mutualFundOrderData.StatusMessage);
                else
                    writer.WriteNull("status_message");

            if (mutualFundOrderData.OrderTimestampOption.IsSet)
                if (mutualFundOrderData.OrderTimestampOption.Value != null)
                    writer.WriteString("order_timestamp", mutualFundOrderData.OrderTimestamp);
                else
                    writer.WriteNull("order_timestamp");

            if (mutualFundOrderData.ExchangeTimestampOption.IsSet)
                if (mutualFundOrderData.ExchangeTimestampOption.Value != null)
                    writer.WriteString("exchange_timestamp", mutualFundOrderData.ExchangeTimestamp);
                else
                    writer.WriteNull("exchange_timestamp");

            if (mutualFundOrderData.SettlementIdOption.IsSet)
                if (mutualFundOrderData.SettlementIdOption.Value != null)
                    writer.WriteString("settlement_id", mutualFundOrderData.SettlementId);
                else
                    writer.WriteNull("settlement_id");

            if (mutualFundOrderData.TransactionTypeOption.IsSet)
                if (mutualFundOrderData.TransactionTypeOption.Value != null)
                    writer.WriteString("transaction_type", mutualFundOrderData.TransactionType);
                else
                    writer.WriteNull("transaction_type");

            if (mutualFundOrderData.PurchaseTypeOption.IsSet)
                if (mutualFundOrderData.PurchaseTypeOption.Value != null)
                    writer.WriteString("purchase_type", mutualFundOrderData.PurchaseType);
                else
                    writer.WriteNull("purchase_type");

            if (mutualFundOrderData.LastPriceOption.IsSet)
                if (mutualFundOrderData.LastPriceOption.Value != null)
                    writer.WriteNumber("last_price", mutualFundOrderData.LastPriceOption.Value!.Value);
                else
                    writer.WriteNull("last_price");

            if (mutualFundOrderData.AveragePriceOption.IsSet)
                if (mutualFundOrderData.AveragePriceOption.Value != null)
                    writer.WriteNumber("average_price", mutualFundOrderData.AveragePriceOption.Value!.Value);
                else
                    writer.WriteNull("average_price");

            if (mutualFundOrderData.LastPriceDateOption.IsSet)
                if (mutualFundOrderData.LastPriceDateOption.Value != null)
                    writer.WriteString("last_price_date", mutualFundOrderData.LastPriceDate);
                else
                    writer.WriteNull("last_price_date");
        }
    }
}
