// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// PositionData
    /// </summary>
    public partial class PositionData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PositionData" /> class.
        /// </summary>
        /// <param name="exchange">Exchange to which the order is associated</param>
        /// <param name="multiplier">The quantity/lot size multiplier used for calculating P&amp;Ls</param>
        /// <param name="value">Net value of the position</param>
        /// <param name="pnl">Profit and loss - net returns on the position</param>
        /// <param name="product">Shows if the order was either Intraday, Delivery, CO or OCO</param>
        /// <param name="instrumentToken">Key issued by Upstox for the instrument</param>
        /// <param name="averagePrice">Average price at which the net position quantity was acquired</param>
        /// <param name="buyValue">Net value of the bought quantities</param>
        /// <param name="overnightQuantity">Quantity held previously and carried forward over night</param>
        /// <param name="dayBuyValue">Amount at which the quantity is bought during the day</param>
        /// <param name="dayBuyPrice">Average price at which the day qty was bought. Default is empty string</param>
        /// <param name="overnightBuyAmount">Amount at which the quantity was bought in the previous session</param>
        /// <param name="overnightBuyQuantity">Quantity bought in the previous session</param>
        /// <param name="dayBuyQuantity">Quantity bought during the day</param>
        /// <param name="daySellValue">Amount at which the quantity is sold during the day</param>
        /// <param name="daySellPrice">Average price at which the day quantity was sold</param>
        /// <param name="overnightSellAmount">Amount at which the quantity was sold in the previous session</param>
        /// <param name="overnightSellQuantity">Quantity sold short in the previous session</param>
        /// <param name="daySellQuantity">Quantity sold during the day</param>
        /// <param name="quantity">Quantity left after nullifying Day and CF buy quantity towards Day and CF sell quantity</param>
        /// <param name="lastPrice">Last traded market price of the instrument</param>
        /// <param name="unrealised">Day PnL generated against open positions</param>
        /// <param name="realised">Day PnL generated against closed positions</param>
        /// <param name="sellValue">Net value of the sold quantities</param>
        /// <param name="tradingSymbol">Shows the trading symbol of the instrument</param>
        /// <param name="closePrice">Closing price of the instrument from the last trading day</param>
        /// <param name="buyPrice">Average price at which quantities were bought</param>
        /// <param name="sellPrice">Average price at which quantities were sold</param>
        [JsonConstructor]
        internal PositionData(Option<ExchangeEnum?> exchange = default, Option<float?> multiplier = default, Option<float?> value = default, Option<float?> pnl = default, Option<string?> product = default, Option<string?> instrumentToken = default, Option<float?> averagePrice = default, Option<float?> buyValue = default, Option<int?> overnightQuantity = default, Option<float?> dayBuyValue = default, Option<float?> dayBuyPrice = default, Option<float?> overnightBuyAmount = default, Option<int?> overnightBuyQuantity = default, Option<int?> dayBuyQuantity = default, Option<float?> daySellValue = default, Option<float?> daySellPrice = default, Option<float?> overnightSellAmount = default, Option<int?> overnightSellQuantity = default, Option<int?> daySellQuantity = default, Option<int?> quantity = default, Option<float?> lastPrice = default, Option<float?> unrealised = default, Option<float?> realised = default, Option<float?> sellValue = default, Option<string?> tradingSymbol = default, Option<float?> closePrice = default, Option<float?> buyPrice = default, Option<float?> sellPrice = default)
        {
            ExchangeOption = exchange;
            MultiplierOption = multiplier;
            ValueOption = value;
            PnlOption = pnl;
            ProductOption = product;
            InstrumentTokenOption = instrumentToken;
            AveragePriceOption = averagePrice;
            BuyValueOption = buyValue;
            OvernightQuantityOption = overnightQuantity;
            DayBuyValueOption = dayBuyValue;
            DayBuyPriceOption = dayBuyPrice;
            OvernightBuyAmountOption = overnightBuyAmount;
            OvernightBuyQuantityOption = overnightBuyQuantity;
            DayBuyQuantityOption = dayBuyQuantity;
            DaySellValueOption = daySellValue;
            DaySellPriceOption = daySellPrice;
            OvernightSellAmountOption = overnightSellAmount;
            OvernightSellQuantityOption = overnightSellQuantity;
            DaySellQuantityOption = daySellQuantity;
            QuantityOption = quantity;
            LastPriceOption = lastPrice;
            UnrealisedOption = unrealised;
            RealisedOption = realised;
            SellValueOption = sellValue;
            TradingSymbolOption = tradingSymbol;
            ClosePriceOption = closePrice;
            BuyPriceOption = buyPrice;
            SellPriceOption = sellPrice;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Exchange to which the order is associated
        /// </summary>
        /// <value>Exchange to which the order is associated</value>
        public enum ExchangeEnum
        {
            /// <summary>
            /// Enum NSE for value: NSE
            /// </summary>
            NSE = 1,

            /// <summary>
            /// Enum NFO for value: NFO
            /// </summary>
            NFO = 2,

            /// <summary>
            /// Enum CDS for value: CDS
            /// </summary>
            CDS = 3,

            /// <summary>
            /// Enum BSE for value: BSE
            /// </summary>
            BSE = 4,

            /// <summary>
            /// Enum BFO for value: BFO
            /// </summary>
            BFO = 5,

            /// <summary>
            /// Enum BCD for value: BCD
            /// </summary>
            BCD = 6,

            /// <summary>
            /// Enum MCX for value: MCX
            /// </summary>
            MCX = 7,

            /// <summary>
            /// Enum NSCOM for value: NSCOM
            /// </summary>
            NSCOM = 8
        }

        /// <summary>
        /// Returns a <see cref="ExchangeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static ExchangeEnum ExchangeEnumFromString(string value)
        {
            if (value.Equals("NSE"))
                return ExchangeEnum.NSE;

            if (value.Equals("NFO"))
                return ExchangeEnum.NFO;

            if (value.Equals("CDS"))
                return ExchangeEnum.CDS;

            if (value.Equals("BSE"))
                return ExchangeEnum.BSE;

            if (value.Equals("BFO"))
                return ExchangeEnum.BFO;

            if (value.Equals("BCD"))
                return ExchangeEnum.BCD;

            if (value.Equals("MCX"))
                return ExchangeEnum.MCX;

            if (value.Equals("NSCOM"))
                return ExchangeEnum.NSCOM;

            throw new NotImplementedException($"Could not convert value to type ExchangeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="ExchangeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ExchangeEnum? ExchangeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("NSE"))
                return ExchangeEnum.NSE;

            if (value.Equals("NFO"))
                return ExchangeEnum.NFO;

            if (value.Equals("CDS"))
                return ExchangeEnum.CDS;

            if (value.Equals("BSE"))
                return ExchangeEnum.BSE;

            if (value.Equals("BFO"))
                return ExchangeEnum.BFO;

            if (value.Equals("BCD"))
                return ExchangeEnum.BCD;

            if (value.Equals("MCX"))
                return ExchangeEnum.MCX;

            if (value.Equals("NSCOM"))
                return ExchangeEnum.NSCOM;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ExchangeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string? ExchangeEnumToJsonValue(ExchangeEnum? value)
        {
            if (value == null)
                return null;

            if (value == ExchangeEnum.NSE)
                return "NSE";

            if (value == ExchangeEnum.NFO)
                return "NFO";

            if (value == ExchangeEnum.CDS)
                return "CDS";

            if (value == ExchangeEnum.BSE)
                return "BSE";

            if (value == ExchangeEnum.BFO)
                return "BFO";

            if (value == ExchangeEnum.BCD)
                return "BCD";

            if (value == ExchangeEnum.MCX)
                return "MCX";

            if (value == ExchangeEnum.NSCOM)
                return "NSCOM";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Exchange
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ExchangeEnum?> ExchangeOption { get; }

        /// <summary>
        /// Exchange to which the order is associated
        /// </summary>
        /// <value>Exchange to which the order is associated</value>
        /* <example>NSE</example> */
        [JsonPropertyName("exchange")]
        public ExchangeEnum? Exchange { get { return this.ExchangeOption; } }

        /// <summary>
        /// Used to track the state of Multiplier
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> MultiplierOption { get; }

        /// <summary>
        /// The quantity/lot size multiplier used for calculating P&amp;Ls
        /// </summary>
        /// <value>The quantity/lot size multiplier used for calculating P&amp;Ls</value>
        /* <example>1</example> */
        [JsonPropertyName("multiplier")]
        public float? Multiplier { get { return this.MultiplierOption; } }

        /// <summary>
        /// Used to track the state of Value
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> ValueOption { get; }

        /// <summary>
        /// Net value of the position
        /// </summary>
        /// <value>Net value of the position</value>
        /* <example>120</example> */
        [JsonPropertyName("value")]
        public float? Value { get { return this.ValueOption; } }

        /// <summary>
        /// Used to track the state of Pnl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> PnlOption { get; }

        /// <summary>
        /// Profit and loss - net returns on the position
        /// </summary>
        /// <value>Profit and loss - net returns on the position</value>
        /* <example>121.01</example> */
        [JsonPropertyName("pnl")]
        public float? Pnl { get { return this.PnlOption; } }

        /// <summary>
        /// Used to track the state of Product
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ProductOption { get; }

        /// <summary>
        /// Shows if the order was either Intraday, Delivery, CO or OCO
        /// </summary>
        /// <value>Shows if the order was either Intraday, Delivery, CO or OCO</value>
        /* <example>D</example> */
        [JsonPropertyName("product")]
        public string? Product { get { return this.ProductOption; } }

        /// <summary>
        /// Used to track the state of InstrumentToken
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstrumentTokenOption { get; }

        /// <summary>
        /// Key issued by Upstox for the instrument
        /// </summary>
        /// <value>Key issued by Upstox for the instrument</value>
        /* <example>151064324</example> */
        [JsonPropertyName("instrument_token")]
        public string? InstrumentToken { get { return this.InstrumentTokenOption; } }

        /// <summary>
        /// Used to track the state of AveragePrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> AveragePriceOption { get; }

        /// <summary>
        /// Average price at which the net position quantity was acquired
        /// </summary>
        /// <value>Average price at which the net position quantity was acquired</value>
        /* <example>120.01</example> */
        [JsonPropertyName("average_price")]
        public float? AveragePrice { get { return this.AveragePriceOption; } }

        /// <summary>
        /// Used to track the state of BuyValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> BuyValueOption { get; }

        /// <summary>
        /// Net value of the bought quantities
        /// </summary>
        /// <value>Net value of the bought quantities</value>
        /* <example>120</example> */
        [JsonPropertyName("buy_value")]
        public float? BuyValue { get { return this.BuyValueOption; } }

        /// <summary>
        /// Used to track the state of OvernightQuantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OvernightQuantityOption { get; }

        /// <summary>
        /// Quantity held previously and carried forward over night
        /// </summary>
        /// <value>Quantity held previously and carried forward over night</value>
        /* <example>1</example> */
        [JsonPropertyName("overnight_quantity")]
        public int? OvernightQuantity { get { return this.OvernightQuantityOption; } }

        /// <summary>
        /// Used to track the state of DayBuyValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> DayBuyValueOption { get; }

        /// <summary>
        /// Amount at which the quantity is bought during the day
        /// </summary>
        /// <value>Amount at which the quantity is bought during the day</value>
        /* <example>120.01</example> */
        [JsonPropertyName("day_buy_value")]
        public float? DayBuyValue { get { return this.DayBuyValueOption; } }

        /// <summary>
        /// Used to track the state of DayBuyPrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> DayBuyPriceOption { get; }

        /// <summary>
        /// Average price at which the day qty was bought. Default is empty string
        /// </summary>
        /// <value>Average price at which the day qty was bought. Default is empty string</value>
        /* <example>120.01</example> */
        [JsonPropertyName("day_buy_price")]
        public float? DayBuyPrice { get { return this.DayBuyPriceOption; } }

        /// <summary>
        /// Used to track the state of OvernightBuyAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> OvernightBuyAmountOption { get; }

        /// <summary>
        /// Amount at which the quantity was bought in the previous session
        /// </summary>
        /// <value>Amount at which the quantity was bought in the previous session</value>
        /* <example>12</example> */
        [JsonPropertyName("overnight_buy_amount")]
        public float? OvernightBuyAmount { get { return this.OvernightBuyAmountOption; } }

        /// <summary>
        /// Used to track the state of OvernightBuyQuantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OvernightBuyQuantityOption { get; }

        /// <summary>
        /// Quantity bought in the previous session
        /// </summary>
        /// <value>Quantity bought in the previous session</value>
        /* <example>12</example> */
        [JsonPropertyName("overnight_buy_quantity")]
        public int? OvernightBuyQuantity { get { return this.OvernightBuyQuantityOption; } }

        /// <summary>
        /// Used to track the state of DayBuyQuantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DayBuyQuantityOption { get; }

        /// <summary>
        /// Quantity bought during the day
        /// </summary>
        /// <value>Quantity bought during the day</value>
        /* <example>1</example> */
        [JsonPropertyName("day_buy_quantity")]
        public int? DayBuyQuantity { get { return this.DayBuyQuantityOption; } }

        /// <summary>
        /// Used to track the state of DaySellValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> DaySellValueOption { get; }

        /// <summary>
        /// Amount at which the quantity is sold during the day
        /// </summary>
        /// <value>Amount at which the quantity is sold during the day</value>
        /* <example>0</example> */
        [JsonPropertyName("day_sell_value")]
        public float? DaySellValue { get { return this.DaySellValueOption; } }

        /// <summary>
        /// Used to track the state of DaySellPrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> DaySellPriceOption { get; }

        /// <summary>
        /// Average price at which the day quantity was sold
        /// </summary>
        /// <value>Average price at which the day quantity was sold</value>
        /* <example>0</example> */
        [JsonPropertyName("day_sell_price")]
        public float? DaySellPrice { get { return this.DaySellPriceOption; } }

        /// <summary>
        /// Used to track the state of OvernightSellAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> OvernightSellAmountOption { get; }

        /// <summary>
        /// Amount at which the quantity was sold in the previous session
        /// </summary>
        /// <value>Amount at which the quantity was sold in the previous session</value>
        /* <example>120.01</example> */
        [JsonPropertyName("overnight_sell_amount")]
        public float? OvernightSellAmount { get { return this.OvernightSellAmountOption; } }

        /// <summary>
        /// Used to track the state of OvernightSellQuantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OvernightSellQuantityOption { get; }

        /// <summary>
        /// Quantity sold short in the previous session
        /// </summary>
        /// <value>Quantity sold short in the previous session</value>
        /* <example>0</example> */
        [JsonPropertyName("overnight_sell_quantity")]
        public int? OvernightSellQuantity { get { return this.OvernightSellQuantityOption; } }

        /// <summary>
        /// Used to track the state of DaySellQuantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DaySellQuantityOption { get; }

        /// <summary>
        /// Quantity sold during the day
        /// </summary>
        /// <value>Quantity sold during the day</value>
        /* <example>0</example> */
        [JsonPropertyName("day_sell_quantity")]
        public int? DaySellQuantity { get { return this.DaySellQuantityOption; } }

        /// <summary>
        /// Used to track the state of Quantity
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> QuantityOption { get; }

        /// <summary>
        /// Quantity left after nullifying Day and CF buy quantity towards Day and CF sell quantity
        /// </summary>
        /// <value>Quantity left after nullifying Day and CF buy quantity towards Day and CF sell quantity</value>
        /* <example>2</example> */
        [JsonPropertyName("quantity")]
        public int? Quantity { get { return this.QuantityOption; } }

        /// <summary>
        /// Used to track the state of LastPrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> LastPriceOption { get; }

        /// <summary>
        /// Last traded market price of the instrument
        /// </summary>
        /// <value>Last traded market price of the instrument</value>
        /* <example>120.01</example> */
        [JsonPropertyName("last_price")]
        public float? LastPrice { get { return this.LastPriceOption; } }

        /// <summary>
        /// Used to track the state of Unrealised
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> UnrealisedOption { get; }

        /// <summary>
        /// Day PnL generated against open positions
        /// </summary>
        /// <value>Day PnL generated against open positions</value>
        /* <example>121.01</example> */
        [JsonPropertyName("unrealised")]
        public float? Unrealised { get { return this.UnrealisedOption; } }

        /// <summary>
        /// Used to track the state of Realised
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> RealisedOption { get; }

        /// <summary>
        /// Day PnL generated against closed positions
        /// </summary>
        /// <value>Day PnL generated against closed positions</value>
        /* <example>0</example> */
        [JsonPropertyName("realised")]
        public float? Realised { get { return this.RealisedOption; } }

        /// <summary>
        /// Used to track the state of SellValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> SellValueOption { get; }

        /// <summary>
        /// Net value of the sold quantities
        /// </summary>
        /// <value>Net value of the sold quantities</value>
        /* <example>0</example> */
        [JsonPropertyName("sell_value")]
        public float? SellValue { get { return this.SellValueOption; } }

        /// <summary>
        /// Used to track the state of TradingSymbol
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TradingSymbolOption { get; }

        /// <summary>
        /// Shows the trading symbol of the instrument
        /// </summary>
        /// <value>Shows the trading symbol of the instrument</value>
        /* <example>GMR</example> */
        [JsonPropertyName("trading_symbol")]
        public string? TradingSymbol { get { return this.TradingSymbolOption; } }

        /// <summary>
        /// Used to track the state of ClosePrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> ClosePriceOption { get; }

        /// <summary>
        /// Closing price of the instrument from the last trading day
        /// </summary>
        /// <value>Closing price of the instrument from the last trading day</value>
        /* <example>102.0</example> */
        [JsonPropertyName("close_price")]
        public float? ClosePrice { get { return this.ClosePriceOption; } }

        /// <summary>
        /// Used to track the state of BuyPrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> BuyPriceOption { get; }

        /// <summary>
        /// Average price at which quantities were bought
        /// </summary>
        /// <value>Average price at which quantities were bought</value>
        /* <example>102.0</example> */
        [JsonPropertyName("buy_price")]
        public float? BuyPrice { get { return this.BuyPriceOption; } }

        /// <summary>
        /// Used to track the state of SellPrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<float?> SellPriceOption { get; }

        /// <summary>
        /// Average price at which quantities were sold
        /// </summary>
        /// <value>Average price at which quantities were sold</value>
        /* <example>102.0</example> */
        [JsonPropertyName("sell_price")]
        public float? SellPrice { get { return this.SellPriceOption; } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PositionData {\n");
            sb.Append("  Exchange: ").Append(Exchange).Append("\n");
            sb.Append("  Multiplier: ").Append(Multiplier).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Pnl: ").Append(Pnl).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  InstrumentToken: ").Append(InstrumentToken).Append("\n");
            sb.Append("  AveragePrice: ").Append(AveragePrice).Append("\n");
            sb.Append("  BuyValue: ").Append(BuyValue).Append("\n");
            sb.Append("  OvernightQuantity: ").Append(OvernightQuantity).Append("\n");
            sb.Append("  DayBuyValue: ").Append(DayBuyValue).Append("\n");
            sb.Append("  DayBuyPrice: ").Append(DayBuyPrice).Append("\n");
            sb.Append("  OvernightBuyAmount: ").Append(OvernightBuyAmount).Append("\n");
            sb.Append("  OvernightBuyQuantity: ").Append(OvernightBuyQuantity).Append("\n");
            sb.Append("  DayBuyQuantity: ").Append(DayBuyQuantity).Append("\n");
            sb.Append("  DaySellValue: ").Append(DaySellValue).Append("\n");
            sb.Append("  DaySellPrice: ").Append(DaySellPrice).Append("\n");
            sb.Append("  OvernightSellAmount: ").Append(OvernightSellAmount).Append("\n");
            sb.Append("  OvernightSellQuantity: ").Append(OvernightSellQuantity).Append("\n");
            sb.Append("  DaySellQuantity: ").Append(DaySellQuantity).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  LastPrice: ").Append(LastPrice).Append("\n");
            sb.Append("  Unrealised: ").Append(Unrealised).Append("\n");
            sb.Append("  Realised: ").Append(Realised).Append("\n");
            sb.Append("  SellValue: ").Append(SellValue).Append("\n");
            sb.Append("  TradingSymbol: ").Append(TradingSymbol).Append("\n");
            sb.Append("  ClosePrice: ").Append(ClosePrice).Append("\n");
            sb.Append("  BuyPrice: ").Append(BuyPrice).Append("\n");
            sb.Append("  SellPrice: ").Append(SellPrice).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PositionData" />
    /// </summary>
    public class PositionDataJsonConverter : JsonConverter<PositionData>
    {
        /// <summary>
        /// Deserializes json to <see cref="PositionData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PositionData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PositionData.ExchangeEnum?> exchange = default;
            Option<float?> multiplier = default;
            Option<float?> value = default;
            Option<float?> pnl = default;
            Option<string?> product = default;
            Option<string?> instrumentToken = default;
            Option<float?> averagePrice = default;
            Option<float?> buyValue = default;
            Option<int?> overnightQuantity = default;
            Option<float?> dayBuyValue = default;
            Option<float?> dayBuyPrice = default;
            Option<float?> overnightBuyAmount = default;
            Option<int?> overnightBuyQuantity = default;
            Option<int?> dayBuyQuantity = default;
            Option<float?> daySellValue = default;
            Option<float?> daySellPrice = default;
            Option<float?> overnightSellAmount = default;
            Option<int?> overnightSellQuantity = default;
            Option<int?> daySellQuantity = default;
            Option<int?> quantity = default;
            Option<float?> lastPrice = default;
            Option<float?> unrealised = default;
            Option<float?> realised = default;
            Option<float?> sellValue = default;
            Option<string?> tradingSymbol = default;
            Option<float?> closePrice = default;
            Option<float?> buyPrice = default;
            Option<float?> sellPrice = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "exchange":
                            string? exchangeRawValue = utf8JsonReader.GetString();
                            if (exchangeRawValue != null)
                                exchange = new Option<PositionData.ExchangeEnum?>(PositionData.ExchangeEnumFromStringOrDefault(exchangeRawValue));
                            break;
                        case "multiplier":
                            multiplier = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "value":
                            value = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "pnl":
                            pnl = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "product":
                            product = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "instrument_token":
                            instrumentToken = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "average_price":
                            averagePrice = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "buy_value":
                            buyValue = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "overnight_quantity":
                            overnightQuantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "day_buy_value":
                            dayBuyValue = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "day_buy_price":
                            dayBuyPrice = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "overnight_buy_amount":
                            overnightBuyAmount = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "overnight_buy_quantity":
                            overnightBuyQuantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "day_buy_quantity":
                            dayBuyQuantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "day_sell_value":
                            daySellValue = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "day_sell_price":
                            daySellPrice = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "overnight_sell_amount":
                            overnightSellAmount = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "overnight_sell_quantity":
                            overnightSellQuantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "day_sell_quantity":
                            daySellQuantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "quantity":
                            quantity = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "last_price":
                            lastPrice = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "unrealised":
                            unrealised = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "realised":
                            realised = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "sell_value":
                            sellValue = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "trading_symbol":
                            tradingSymbol = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "close_price":
                            closePrice = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "buy_price":
                            buyPrice = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        case "sell_price":
                            sellPrice = new Option<float?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (float?)null : (float)utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new PositionData(exchange, multiplier, value, pnl, product, instrumentToken, averagePrice, buyValue, overnightQuantity, dayBuyValue, dayBuyPrice, overnightBuyAmount, overnightBuyQuantity, dayBuyQuantity, daySellValue, daySellPrice, overnightSellAmount, overnightSellQuantity, daySellQuantity, quantity, lastPrice, unrealised, realised, sellValue, tradingSymbol, closePrice, buyPrice, sellPrice);
        }

        /// <summary>
        /// Serializes a <see cref="PositionData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="positionData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PositionData positionData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, positionData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PositionData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="positionData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PositionData positionData, JsonSerializerOptions jsonSerializerOptions)
        {
            var exchangeRawValue = PositionData.ExchangeEnumToJsonValue(positionData.ExchangeOption.Value!.Value);
            if (exchangeRawValue != null)
                writer.WriteString("exchange", exchangeRawValue);
            else
                writer.WriteNull("exchange");

            if (positionData.MultiplierOption.IsSet)
                if (positionData.MultiplierOption.Value != null)
                    writer.WriteNumber("multiplier", positionData.MultiplierOption.Value!.Value);
                else
                    writer.WriteNull("multiplier");

            if (positionData.ValueOption.IsSet)
                if (positionData.ValueOption.Value != null)
                    writer.WriteNumber("value", positionData.ValueOption.Value!.Value);
                else
                    writer.WriteNull("value");

            if (positionData.PnlOption.IsSet)
                if (positionData.PnlOption.Value != null)
                    writer.WriteNumber("pnl", positionData.PnlOption.Value!.Value);
                else
                    writer.WriteNull("pnl");

            if (positionData.ProductOption.IsSet)
                if (positionData.ProductOption.Value != null)
                    writer.WriteString("product", positionData.Product);
                else
                    writer.WriteNull("product");

            if (positionData.InstrumentTokenOption.IsSet)
                if (positionData.InstrumentTokenOption.Value != null)
                    writer.WriteString("instrument_token", positionData.InstrumentToken);
                else
                    writer.WriteNull("instrument_token");

            if (positionData.AveragePriceOption.IsSet)
                if (positionData.AveragePriceOption.Value != null)
                    writer.WriteNumber("average_price", positionData.AveragePriceOption.Value!.Value);
                else
                    writer.WriteNull("average_price");

            if (positionData.BuyValueOption.IsSet)
                if (positionData.BuyValueOption.Value != null)
                    writer.WriteNumber("buy_value", positionData.BuyValueOption.Value!.Value);
                else
                    writer.WriteNull("buy_value");

            if (positionData.OvernightQuantityOption.IsSet)
                if (positionData.OvernightQuantityOption.Value != null)
                    writer.WriteNumber("overnight_quantity", positionData.OvernightQuantityOption.Value!.Value);
                else
                    writer.WriteNull("overnight_quantity");

            if (positionData.DayBuyValueOption.IsSet)
                if (positionData.DayBuyValueOption.Value != null)
                    writer.WriteNumber("day_buy_value", positionData.DayBuyValueOption.Value!.Value);
                else
                    writer.WriteNull("day_buy_value");

            if (positionData.DayBuyPriceOption.IsSet)
                if (positionData.DayBuyPriceOption.Value != null)
                    writer.WriteNumber("day_buy_price", positionData.DayBuyPriceOption.Value!.Value);
                else
                    writer.WriteNull("day_buy_price");

            if (positionData.OvernightBuyAmountOption.IsSet)
                if (positionData.OvernightBuyAmountOption.Value != null)
                    writer.WriteNumber("overnight_buy_amount", positionData.OvernightBuyAmountOption.Value!.Value);
                else
                    writer.WriteNull("overnight_buy_amount");

            if (positionData.OvernightBuyQuantityOption.IsSet)
                if (positionData.OvernightBuyQuantityOption.Value != null)
                    writer.WriteNumber("overnight_buy_quantity", positionData.OvernightBuyQuantityOption.Value!.Value);
                else
                    writer.WriteNull("overnight_buy_quantity");

            if (positionData.DayBuyQuantityOption.IsSet)
                if (positionData.DayBuyQuantityOption.Value != null)
                    writer.WriteNumber("day_buy_quantity", positionData.DayBuyQuantityOption.Value!.Value);
                else
                    writer.WriteNull("day_buy_quantity");

            if (positionData.DaySellValueOption.IsSet)
                if (positionData.DaySellValueOption.Value != null)
                    writer.WriteNumber("day_sell_value", positionData.DaySellValueOption.Value!.Value);
                else
                    writer.WriteNull("day_sell_value");

            if (positionData.DaySellPriceOption.IsSet)
                if (positionData.DaySellPriceOption.Value != null)
                    writer.WriteNumber("day_sell_price", positionData.DaySellPriceOption.Value!.Value);
                else
                    writer.WriteNull("day_sell_price");

            if (positionData.OvernightSellAmountOption.IsSet)
                if (positionData.OvernightSellAmountOption.Value != null)
                    writer.WriteNumber("overnight_sell_amount", positionData.OvernightSellAmountOption.Value!.Value);
                else
                    writer.WriteNull("overnight_sell_amount");

            if (positionData.OvernightSellQuantityOption.IsSet)
                if (positionData.OvernightSellQuantityOption.Value != null)
                    writer.WriteNumber("overnight_sell_quantity", positionData.OvernightSellQuantityOption.Value!.Value);
                else
                    writer.WriteNull("overnight_sell_quantity");

            if (positionData.DaySellQuantityOption.IsSet)
                if (positionData.DaySellQuantityOption.Value != null)
                    writer.WriteNumber("day_sell_quantity", positionData.DaySellQuantityOption.Value!.Value);
                else
                    writer.WriteNull("day_sell_quantity");

            if (positionData.QuantityOption.IsSet)
                if (positionData.QuantityOption.Value != null)
                    writer.WriteNumber("quantity", positionData.QuantityOption.Value!.Value);
                else
                    writer.WriteNull("quantity");

            if (positionData.LastPriceOption.IsSet)
                if (positionData.LastPriceOption.Value != null)
                    writer.WriteNumber("last_price", positionData.LastPriceOption.Value!.Value);
                else
                    writer.WriteNull("last_price");

            if (positionData.UnrealisedOption.IsSet)
                if (positionData.UnrealisedOption.Value != null)
                    writer.WriteNumber("unrealised", positionData.UnrealisedOption.Value!.Value);
                else
                    writer.WriteNull("unrealised");

            if (positionData.RealisedOption.IsSet)
                if (positionData.RealisedOption.Value != null)
                    writer.WriteNumber("realised", positionData.RealisedOption.Value!.Value);
                else
                    writer.WriteNull("realised");

            if (positionData.SellValueOption.IsSet)
                if (positionData.SellValueOption.Value != null)
                    writer.WriteNumber("sell_value", positionData.SellValueOption.Value!.Value);
                else
                    writer.WriteNull("sell_value");

            if (positionData.TradingSymbolOption.IsSet)
                if (positionData.TradingSymbolOption.Value != null)
                    writer.WriteString("trading_symbol", positionData.TradingSymbol);
                else
                    writer.WriteNull("trading_symbol");

            if (positionData.ClosePriceOption.IsSet)
                if (positionData.ClosePriceOption.Value != null)
                    writer.WriteNumber("close_price", positionData.ClosePriceOption.Value!.Value);
                else
                    writer.WriteNull("close_price");

            if (positionData.BuyPriceOption.IsSet)
                if (positionData.BuyPriceOption.Value != null)
                    writer.WriteNumber("buy_price", positionData.BuyPriceOption.Value!.Value);
                else
                    writer.WriteNull("buy_price");

            if (positionData.SellPriceOption.IsSet)
                if (positionData.SellPriceOption.Value != null)
                    writer.WriteNumber("sell_price", positionData.SellPriceOption.Value!.Value);
                else
                    writer.WriteNull("sell_price");
        }
    }
}
