// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// PutCallOptionChainData
    /// </summary>
    public partial class PutCallOptionChainData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PutCallOptionChainData" /> class.
        /// </summary>
        /// <param name="instrumentKey">instrumentKey</param>
        /// <param name="marketData">marketData</param>
        /// <param name="optionGreeks">optionGreeks</param>
        [JsonConstructor]
        public PutCallOptionChainData(Option<string?> instrumentKey = default, Option<MarketData?> marketData = default, Option<AnalyticsData?> optionGreeks = default)
        {
            InstrumentKeyOption = instrumentKey;
            MarketDataOption = marketData;
            OptionGreeksOption = optionGreeks;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of InstrumentKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InstrumentKeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets InstrumentKey
        /// </summary>
        [JsonPropertyName("instrument_key")]
        public string? InstrumentKey { get { return this.InstrumentKeyOption; } set { this.InstrumentKeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of MarketData
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MarketData?> MarketDataOption { get; private set; }

        /// <summary>
        /// Gets or Sets MarketData
        /// </summary>
        [JsonPropertyName("market_data")]
        public MarketData? MarketData { get { return this.MarketDataOption; } set { this.MarketDataOption = new(value); } }

        /// <summary>
        /// Used to track the state of OptionGreeks
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AnalyticsData?> OptionGreeksOption { get; private set; }

        /// <summary>
        /// Gets or Sets OptionGreeks
        /// </summary>
        [JsonPropertyName("option_greeks")]
        public AnalyticsData? OptionGreeks { get { return this.OptionGreeksOption; } set { this.OptionGreeksOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PutCallOptionChainData {\n");
            sb.Append("  InstrumentKey: ").Append(InstrumentKey).Append("\n");
            sb.Append("  MarketData: ").Append(MarketData).Append("\n");
            sb.Append("  OptionGreeks: ").Append(OptionGreeks).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PutCallOptionChainData" />
    /// </summary>
    public class PutCallOptionChainDataJsonConverter : JsonConverter<PutCallOptionChainData>
    {
        /// <summary>
        /// Deserializes json to <see cref="PutCallOptionChainData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PutCallOptionChainData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> instrumentKey = default;
            Option<MarketData?> marketData = default;
            Option<AnalyticsData?> optionGreeks = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "instrument_key":
                            instrumentKey = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "market_data":
                            marketData = new Option<MarketData?>(JsonSerializer.Deserialize<MarketData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "option_greeks":
                            optionGreeks = new Option<AnalyticsData?>(JsonSerializer.Deserialize<AnalyticsData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (marketData.IsSet && marketData.Value == null)
                throw new ArgumentNullException(nameof(marketData), "Property is not nullable for class PutCallOptionChainData.");

            if (optionGreeks.IsSet && optionGreeks.Value == null)
                throw new ArgumentNullException(nameof(optionGreeks), "Property is not nullable for class PutCallOptionChainData.");

            return new PutCallOptionChainData(instrumentKey, marketData, optionGreeks);
        }

        /// <summary>
        /// Serializes a <see cref="PutCallOptionChainData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="putCallOptionChainData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PutCallOptionChainData putCallOptionChainData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, putCallOptionChainData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PutCallOptionChainData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="putCallOptionChainData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PutCallOptionChainData putCallOptionChainData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (putCallOptionChainData.MarketDataOption.IsSet && putCallOptionChainData.MarketData == null)
                throw new ArgumentNullException(nameof(putCallOptionChainData.MarketData), "Property is required for class PutCallOptionChainData.");

            if (putCallOptionChainData.OptionGreeksOption.IsSet && putCallOptionChainData.OptionGreeks == null)
                throw new ArgumentNullException(nameof(putCallOptionChainData.OptionGreeks), "Property is required for class PutCallOptionChainData.");

            if (putCallOptionChainData.InstrumentKeyOption.IsSet)
                if (putCallOptionChainData.InstrumentKeyOption.Value != null)
                    writer.WriteString("instrument_key", putCallOptionChainData.InstrumentKey);
                else
                    writer.WriteNull("instrument_key");

            if (putCallOptionChainData.MarketDataOption.IsSet)
            {
                writer.WritePropertyName("market_data");
                JsonSerializer.Serialize(writer, putCallOptionChainData.MarketData, jsonSerializerOptions);
            }
            if (putCallOptionChainData.OptionGreeksOption.IsSet)
            {
                writer.WritePropertyName("option_greeks");
                JsonSerializer.Serialize(writer, putCallOptionChainData.OptionGreeks, jsonSerializerOptions);
            }
        }
    }
}
