// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// Rule
    /// </summary>
    public partial class Rule
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rule" /> class.
        /// </summary>
        /// <param name="strategy">strategy</param>
        /// <param name="status">status</param>
        /// <param name="message">message</param>
        /// <param name="triggerType">triggerType</param>
        /// <param name="triggerPrice">triggerPrice</param>
        /// <param name="transactionType">transactionType</param>
        /// <param name="orderId">orderId</param>
        /// <param name="trailingGap">trailingGap</param>
        [JsonConstructor]
        public Rule(Option<string?> strategy = default, Option<string?> status = default, Option<string?> message = default, Option<string?> triggerType = default, Option<double?> triggerPrice = default, Option<string?> transactionType = default, Option<string?> orderId = default, Option<double?> trailingGap = default)
        {
            StrategyOption = strategy;
            StatusOption = status;
            MessageOption = message;
            TriggerTypeOption = triggerType;
            TriggerPriceOption = triggerPrice;
            TransactionTypeOption = transactionType;
            OrderIdOption = orderId;
            TrailingGapOption = trailingGap;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Strategy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StrategyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Strategy
        /// </summary>
        [JsonPropertyName("strategy")]
        public string? Strategy { get { return this.StrategyOption; } set { this.StrategyOption = new(value); } }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of TriggerType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TriggerTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets TriggerType
        /// </summary>
        [JsonPropertyName("trigger_type")]
        public string? TriggerType { get { return this.TriggerTypeOption; } set { this.TriggerTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TriggerPrice
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> TriggerPriceOption { get; private set; }

        /// <summary>
        /// Gets or Sets TriggerPrice
        /// </summary>
        [JsonPropertyName("trigger_price")]
        public double? TriggerPrice { get { return this.TriggerPriceOption; } set { this.TriggerPriceOption = new(value); } }

        /// <summary>
        /// Used to track the state of TransactionType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TransactionTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets TransactionType
        /// </summary>
        [JsonPropertyName("transaction_type")]
        public string? TransactionType { get { return this.TransactionTypeOption; } set { this.TransactionTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of OrderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OrderIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [JsonPropertyName("order_id")]
        public string? OrderId { get { return this.OrderIdOption; } set { this.OrderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TrailingGap
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> TrailingGapOption { get; private set; }

        /// <summary>
        /// Gets or Sets TrailingGap
        /// </summary>
        [JsonPropertyName("trailing_gap")]
        public double? TrailingGap { get { return this.TrailingGapOption; } set { this.TrailingGapOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Rule {\n");
            sb.Append("  Strategy: ").Append(Strategy).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  TriggerType: ").Append(TriggerType).Append("\n");
            sb.Append("  TriggerPrice: ").Append(TriggerPrice).Append("\n");
            sb.Append("  TransactionType: ").Append(TransactionType).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  TrailingGap: ").Append(TrailingGap).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Rule" />
    /// </summary>
    public class RuleJsonConverter : JsonConverter<Rule>
    {
        /// <summary>
        /// Deserializes json to <see cref="Rule" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Rule Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> strategy = default;
            Option<string?> status = default;
            Option<string?> message = default;
            Option<string?> triggerType = default;
            Option<double?> triggerPrice = default;
            Option<string?> transactionType = default;
            Option<string?> orderId = default;
            Option<double?> trailingGap = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "strategy":
                            strategy = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "trigger_type":
                            triggerType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "trigger_price":
                            triggerPrice = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        case "transaction_type":
                            transactionType = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "order_id":
                            orderId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "trailing_gap":
                            trailingGap = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new Rule(strategy, status, message, triggerType, triggerPrice, transactionType, orderId, trailingGap);
        }

        /// <summary>
        /// Serializes a <see cref="Rule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Rule rule, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, rule, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Rule" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="rule"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Rule rule, JsonSerializerOptions jsonSerializerOptions)
        {
            if (rule.StrategyOption.IsSet)
                if (rule.StrategyOption.Value != null)
                    writer.WriteString("strategy", rule.Strategy);
                else
                    writer.WriteNull("strategy");

            if (rule.StatusOption.IsSet)
                if (rule.StatusOption.Value != null)
                    writer.WriteString("status", rule.Status);
                else
                    writer.WriteNull("status");

            if (rule.MessageOption.IsSet)
                if (rule.MessageOption.Value != null)
                    writer.WriteString("message", rule.Message);
                else
                    writer.WriteNull("message");

            if (rule.TriggerTypeOption.IsSet)
                if (rule.TriggerTypeOption.Value != null)
                    writer.WriteString("trigger_type", rule.TriggerType);
                else
                    writer.WriteNull("trigger_type");

            if (rule.TriggerPriceOption.IsSet)
                if (rule.TriggerPriceOption.Value != null)
                    writer.WriteNumber("trigger_price", rule.TriggerPriceOption.Value!.Value);
                else
                    writer.WriteNull("trigger_price");

            if (rule.TransactionTypeOption.IsSet)
                if (rule.TransactionTypeOption.Value != null)
                    writer.WriteString("transaction_type", rule.TransactionType);
                else
                    writer.WriteNull("transaction_type");

            if (rule.OrderIdOption.IsSet)
                if (rule.OrderIdOption.Value != null)
                    writer.WriteString("order_id", rule.OrderId);
                else
                    writer.WriteNull("order_id");

            if (rule.TrailingGapOption.IsSet)
                if (rule.TrailingGapOption.Value != null)
                    writer.WriteNumber("trailing_gap", rule.TrailingGapOption.Value!.Value);
                else
                    writer.WriteNull("trailing_gap");
        }
    }
}
