// <auto-generated>
/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using UpstoxClient.Client;

namespace UpstoxClient.Model
{
    /// <summary>
    /// WebsocketAuthRedirectResponseData
    /// </summary>
    public partial class WebsocketAuthRedirectResponseData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebsocketAuthRedirectResponseData" /> class.
        /// </summary>
        /// <param name="authorizedRedirectUri">authorizedRedirectUri</param>
        [JsonConstructor]
        public WebsocketAuthRedirectResponseData(Option<string?> authorizedRedirectUri = default)
        {
            AuthorizedRedirectUriOption = authorizedRedirectUri;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AuthorizedRedirectUri
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AuthorizedRedirectUriOption { get; private set; }

        /// <summary>
        /// Gets or Sets AuthorizedRedirectUri
        /// </summary>
        [JsonPropertyName("authorized_redirect_uri")]
        public string? AuthorizedRedirectUri { get { return this.AuthorizedRedirectUriOption; } set { this.AuthorizedRedirectUriOption = new(value); } }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, JsonElement> AdditionalProperties { get; } = new Dictionary<string, JsonElement>();

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebsocketAuthRedirectResponseData {\n");
            sb.Append("  AuthorizedRedirectUri: ").Append(AuthorizedRedirectUri).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebsocketAuthRedirectResponseData" />
    /// </summary>
    public class WebsocketAuthRedirectResponseDataJsonConverter : JsonConverter<WebsocketAuthRedirectResponseData>
    {
        /// <summary>
        /// Deserializes json to <see cref="WebsocketAuthRedirectResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebsocketAuthRedirectResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> authorizedRedirectUri = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "authorized_redirect_uri":
                            authorizedRedirectUri = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new WebsocketAuthRedirectResponseData(authorizedRedirectUri);
        }

        /// <summary>
        /// Serializes a <see cref="WebsocketAuthRedirectResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="websocketAuthRedirectResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WebsocketAuthRedirectResponseData websocketAuthRedirectResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, websocketAuthRedirectResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebsocketAuthRedirectResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="websocketAuthRedirectResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WebsocketAuthRedirectResponseData websocketAuthRedirectResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (websocketAuthRedirectResponseData.AuthorizedRedirectUriOption.IsSet)
                if (websocketAuthRedirectResponseData.AuthorizedRedirectUriOption.Value != null)
                    writer.WriteString("authorized_redirect_uri", websocketAuthRedirectResponseData.AuthorizedRedirectUri);
                else
                    writer.WriteNull("authorized_redirect_uri");
        }
    }
}
